### ISSUE TITLE
[bug] Magnum not working because of issues in kolla

### ISSUE THREAD

**Issue by flyersa** [osism/issues#1068]
### OSISM release version

latest

### What's the problem?

It is not possible to create magnum k8s templates because it wants some config file. 

Is the same error as this:

https://bugs.launchpad.net/kolla/+bug/2047360

trying to create a coe templates drops:

`2024-07-01 15:48:41.284 10602 ERROR wsme.api [None req-3de00170-e872-41e1-9a66-cb7b8244d870 5d19540b0b2d4720b7567a50f21b9e5d a164c607e81c4918a6e8dd93e42462de - - default -] Server-side error: "Configuration file ~/.kube/config not found". Detail:
Traceback (most recent call last):

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/pykube/config.py", line 111, in from_env
    config = cls.from_service_account()

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/pykube/config.py", line 42, in from_service_account
    with service_account_dir.joinpath("token").open() as fp:

  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,

FileNotFoundError: [Errno 2] No such file or directory: '/var/run/secrets/kubernetes.io/serviceaccount/token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/wsmeext/pecan.py", line 82, in callfunction
    result = f(self, *args, **kwargs)

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/magnum/api/validation.py", line 165, in wrapper
    return func(*args, **kwargs)

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/magnum/api/validation.py", line 128, in wrapper
    return func(*args, **kwargs)

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/magnum/api/validation.py", line 180, in wrapper
    return func(*args, **kwargs)

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/magnum/api/validation.py", line 190, in wrapper
    return func(*args, **kwargs)

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/magnum/api/validation.py", line 84, in wrapper
    driver.Driver.get_driver(*cluster_type)

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/magnum/drivers/common/driver.py", line 123, in get_driver
    definition_map = cls.get_drivers()

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/magnum/drivers/common/driver.py", line 77, in get_drivers
    for cluster_type in def_class().provides:

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/magnum_cluster_api/driver.py", line 47, in __init__
    self.k8s_api = clients.get_pykube_api()

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/magnum_cluster_api/clients.py", line 50, in get_pykube_api
    return pykube.HTTPClient(pykube.KubeConfig.from_env())

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/pykube/config.py", line 114, in from_env
    config = cls.from_file()

  File "/var/lib/kolla/venv/lib/python3.10/site-packages/pykube/config.py", line 93, in from_file
    raise exceptions.PyKubeError(

pykube.exceptions.PyKubeError: Configuration file ~/.kube/config not found
`

### References to existing reports

References to existing bug reports, mailing lists, ...

### Severity

low

### Urgency

low

**Comment by flyersa** [comment]
related:

https://www.roksblog.de/openstack-magnum-cluster-api-driver/

hmm. usual openstack documentation fuckup :/
