### ISSUE TITLE
Test OpenStack 2024.1 deployment & upgrade

### ISSUE THREAD

**Issue by berendt** [osism/issues#1073]
- [ ] also have a look on Neutron/OVN VPNaaS

**Comment by flyersa** [comment]
can you send me detailed instructions please which version i need to pick for the manager etc. and maybe "release upgrade nodes" ?

**Comment by berendt** [comment]
> can you send me detailed instructions please which version i need to pick for the manager etc. and maybe "release upgrade notes" ?

I'll prepare it and put it in here. It will be in the middle of the week.

**Comment by berendt** [comment]
@maliblatt We'll use this issue for the 2024.1 deployment & upgrade test results.

**Comment by berendt** [comment]
Set following parameters in environments/manager/configuration.yml and run make sync afterwards. Commit and push all changes and pull the updated configuration repository on the test cluster. Update the manager with osism update manager as usual. Now you can deploy or upgrade the OpenStack 2024.1 services with osism apply -a upgrade X.

```
ceph_version: quincy
manager_version: latest
openstack_version: 2024.1
```

**Comment by flyersa** [comment]
any particular changelogs for latest that i need to take into consideration upgrading from 7.1.0 to latest ?

ceph btw i will not test, all of our (stackxperts) environments as known use external clusters. I dont think there was alot of change with ceph or ?

**Comment by berendt** [comment]
> any particular changelogs for latest that i need to take into consideration upgrading from 7.1.0 to latest ?

So far I have only seen one secret that you have to add when using Skyline (`prometheus_skyline_password`).

> ceph btw i will not test, all of our (stackxperts) environments as known use external clusters. I dont think there was alot of change with ceph or ?

That‘s fine.

**Comment by maliblatt** [comment]
I have updated an old test environment to 2024.1 without any issues at it seams. Will do some more testing in the next week.
There are indeed only very few kolla-ansible upgrade notes that I had to take into account. One thing I have to take a closer look into is about designate-sink:

`

    The configuration variable designate_enable_notifications_sink has been changed to no, configuring notifications for designate in neutron, nova, and control deployment of designate-sink which is now optional.

    Operators who want to keep the previous behavior should set this to true.
`

I hope next week I can give some more infos about my testings.

**Comment by berendt** [comment]
@maliblatt I think it makes sense to set designate_enable_notifications_sink to true in our defaults to keep the old behavior.

**Comment by flyersa** [comment]
So i installed a completly fresh 2024.1 and also upgraded a 7.1.0 environment. Everything except horizon seems to at least is healthy (no function tests atm) and a few caveeats:

- designate_enable_notifications_sink  true as default would be nice
- gnocchi has no available images ?
- prometheus_skyline_password as already highlighted needs to be added

For Horizon i cant figure out why it doesnt work, it complains about memcache i guess:

```
2024-07-20 13:04:18.001064 /var/lib/kolla/venv/lib/python3.10/site-packages/django/conf/__init__.py:267: RemovedInDjango50Warning: The USE_L10N setting is deprecated. Starting with Django 5.0, localized formatting of data will always be enabled. For example Django will display numbers and dates using the format of the current locale.
2024-07-20 13:04:18.001107   warnings.warn(USE_L10N_DEPRECATED_MSG, RemovedInDjango50Warning)
2024-07-20 13:04:18.122116 /var/lib/kolla/venv/lib/python3.10/site-packages/debreach/__init__.py:6: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
2024-07-20 13:04:18.122145   version_info = version.StrictVersion(__version__).version
2024-07-20 13:04:18.529227 Internal Server Error: /
2024-07-20 13:04:18.529258 Traceback (most recent call last):
2024-07-20 13:04:18.529261   File "/var/lib/kolla/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
2024-07-20 13:04:18.529263     response = get_response(request)
2024-07-20 13:04:18.529264   File "/var/lib/kolla/venv/lib/python3.10/site-packages/horizon/middleware/simultaneous_sessions.py", line 30, in __call__
2024-07-20 13:04:18.529266     self._process_request(request)
2024-07-20 13:04:18.529267   File "/var/lib/kolla/venv/lib/python3.10/site-packages/horizon/middleware/simultaneous_sessions.py", line 37, in _process_request
2024-07-20 13:04:18.529269     cache_value = cache.get(cache_key)
2024-07-20 13:04:18.529270   File "/var/lib/kolla/venv/lib/python3.10/site-packages/django/core/cache/backends/memcached.py", line 75, in get
2024-07-20 13:04:18.529271     return self._cache.get(key, default)
2024-07-20 13:04:18.529273   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymemcache/client/hash.py", line 347, in get
2024-07-20 13:04:18.529275     return self._run_cmd("get", key, default, default=default, **kwargs)
2024-07-20 13:04:18.529276   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymemcache/client/hash.py", line 322, in _run_cmd
2024-07-20 13:04:18.529277     return self._safely_run_func(client, func, default_val, *args, **kwargs)
2024-07-20 13:04:18.529279   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymemcache/client/hash.py", line 211, in _safely_run_func
2024-07-20 13:04:18.529280     result = func(*args, **kwargs)
2024-07-20 13:04:18.529282   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymemcache/client/base.py", line 687, in get
2024-07-20 13:04:18.529283     return self._fetch_cmd(b"get", [key], False, key_prefix=self.key_prefix).get(
2024-07-20 13:04:18.529284   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymemcache/client/base.py", line 1133, in _fetch_cmd
2024-07-20 13:04:18.529286     self._connect()
2024-07-20 13:04:18.529287   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymemcache/client/base.py", line 424, in _connect
2024-07-20 13:04:18.529289     sock.connect(sockaddr)
2024-07-20 13:04:18.529290 ConnectionRefusedError: [Errno 111] Connection refused
```

also it seems reconfigure option or deploy does not copy /opt/configuration/environments/kolla/files/overlays/horizon/custom_local_settings properly to the hosts. Doesnt matter what i change in there, it never ends up on the hosts/containers. 

Tried manually to change CACHE location, has also no effect. memcache is running fine. Would love to know to were it tries to connect...

did your horizon work @maliblatt  ?

**Comment by flyersa** [comment]
Outside of the above i made most tests, magnum cilium works now (despite stil having issues with vexxhost capi driver, but thats not a osism issue).  Skyline has a bug that prevents creation of magnum clusters, it passes the flavor ID instead of the flavor name which magnum expects.

Snapshots, Backups and Backup Restore now works again, Live Migration, Loadbalancers, Image Manager all seems to be in working order.

Not sure how i should test the OVN VPNaaS, its not even yet in kolla. I would at least need an image for the ovn vpn agent. But can play around manual with it, maybe i can get it to work

**Comment by maliblatt** [comment]
@flyersa I have the same situation with horizon. Last week I did only the update itself, but did not test yet the functionality. But I can confirm the same problem with horizon to connect to memcache:

```
2024-07-22 06:59:44.426125 Internal Server Error: /
2024-07-22 06:59:44.426149 Traceback (most recent call last):
2024-07-22 06:59:44.426156   File "/var/lib/kolla/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
2024-07-22 06:59:44.426162     response = get_response(request)
2024-07-22 06:59:44.426168   File "/var/lib/kolla/venv/lib/python3.10/site-packages/horizon/middleware/simultaneous_sessions.py", line 30, in __call__
2024-07-22 06:59:44.426174     self._process_request(request)
2024-07-22 06:59:44.426180   File "/var/lib/kolla/venv/lib/python3.10/site-packages/horizon/middleware/simultaneous_sessions.py", line 37, in _process_request
2024-07-22 06:59:44.426186     cache_value = cache.get(cache_key)
2024-07-22 06:59:44.426191   File "/var/lib/kolla/venv/lib/python3.10/site-packages/django/core/cache/backends/memcached.py", line 75, in get
2024-07-22 06:59:44.426197     return self._cache.get(key, default)
2024-07-22 06:59:44.426203   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymemcache/client/hash.py", line 347, in get
2024-07-22 06:59:44.426208     return self._run_cmd("get", key, default, default=default, **kwargs)
2024-07-22 06:59:44.426214   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymemcache/client/hash.py", line 322, in _run_cmd
2024-07-22 06:59:44.426220     return self._safely_run_func(client, func, default_val, *args, **kwargs)
2024-07-22 06:59:44.426225   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymemcache/client/hash.py", line 211, in _safely_run_func
2024-07-22 06:59:44.426231     result = func(*args, **kwargs)
2024-07-22 06:59:44.426236   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymemcache/client/base.py", line 687, in get
2024-07-22 06:59:44.426242     return self._fetch_cmd(b"get", [key], False, key_prefix=self.key_prefix).get(
2024-07-22 06:59:44.426248   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymemcache/client/base.py", line 1133, in _fetch_cmd
2024-07-22 06:59:44.426253     self._connect()
2024-07-22 06:59:44.426259   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymemcache/client/base.py", line 424, in _connect
2024-07-22 06:59:44.426264     sock.connect(sockaddr)
2024-07-22 06:59:44.426270 ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by maliblatt** [comment]
> 
> `| 8f06be74-f672-58cc-9f5f-84fdfbd7db10 | VPN Agent | hv01 | nova | :-) | UP | neutron-ovn-vpn-agent | `
> 
> If i can get this to work we need to build a proper neutron-ovn-vpn-agent container, or is there one already ?

Take a look into https://review.opendev.org/c/openstack/kolla/+/924302 ... It seems that a Dockerfile is already on the way :-)

**Comment by berendt** [comment]
> > `| 8f06be74-f672-58cc-9f5f-84fdfbd7db10 | VPN Agent | hv01 | nova | :-) | UP | neutron-ovn-vpn-agent | `
> > If i can get this to work we need to build a proper neutron-ovn-vpn-agent container, or is there one already ?
> 
> Take a look into https://review.opendev.org/c/openstack/kolla/+/924302 ... It seems that a Dockerfile is already on the way :-)

Yes, but the whole kolla-ansible part is still missing before that is merged. IMO this is not realistic as a backport for 2024.1. Not directly, at least.

**Comment by berendt** [comment]
> * designate_enable_notifications_sink  true as default would be nice

PR pending. Not quite sure whether we really have this as the default. With Neutron DNS integration, you don't really need it any more.

> * gnocchi has no available images ?

Now online.

**Comment by flyersa** [comment]
> Yes, but the whole kolla-ansible part is still missing before that is merged. IMO this is not realistic as a backport for 2024.1. Not directly, at least.

i dont think we need todo that and wait til its in kolla completed. But i stil want to test the functionality atm. Its not a big problem i can run it for testing in the metadata agent as it has all the parts also installed anyway. So nothing you need todo here atm.

**Comment by berendt** [comment]
> adding this to _9999-custom-settings.py solves the horizon issue:
> 
> ```
> CACHES = {
>     'default': {
>         'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
>         'LOCATION': 'MEMCACHEIP:11211',
>     },
> }
> ```

https://github.com/openstack/kolla-ansible/blob/stable/2024.1/ansible/roles/horizon/templates/_9998-kolla-settings.py.j2#L7-L22

Memcache is only enabled when horizon_backend_database is False. We set horizon_backend_database to True by default. It should not try to reach Memcached at all.

**Comment by flyersa** [comment]
> https://github.com/openstack/kolla-ansible/blob/stable/2024.1/ansible/roles/horizon/templates/_9998-kolla-settings.py.j2#L7-L22
> 
> Memcache is only enabled when horizon_backend_database is False. We set horizon_backend_database to True by default. It should not try to reach Memcached at all.

Well i dont have this variable anywhere set and it stil has this issue

**Comment by berendt** [comment]
> Yes, but the whole kolla-ansible part is still missing before that is merged. IMO this is not realistic as a backport for 2024.1. Not directly, at least.

The missing kolla-ansible part: https://review.opendev.org/c/openstack/kolla-ansible/+/924575

**Comment by berendt** [comment]
This is the default value in Horizon:

```
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': '127.0.0.1:11211',
    },
}
```

SESSION_ENGINE is overwritten by `SESSION_ENGINE = 'django.contrib.sessions.backends.db'` by default. I think `CACHES` has always to be configured with working Memcached servers and not only when `SESSION_ENGINE = 'django.contrib.sessions.backends.cache'`.

**Comment by flyersa** [comment]
so you add the ovn-vpn-agent change now as backport as i see the merge. If the image is available let me know then i test ;)

**Comment by berendt** [comment]
> so you add the ovn-vpn-agent change now as backport as i see the merge. If the image is available let me know then i test ;)

Image + inventory group are available. I have not yet added the part of kolla-ansible as backport.

**Comment by flyersa** [comment]
I can confirm with the backport OVN VPNaaS works. 

![image](https://github.com/user-attachments/assets/d94bed92-475b-47ed-969c-b66902d7f942)

![image](https://github.com/user-attachments/assets/9c82c6f1-7a33-48a5-bba9-4541bc5d592b)

![image](https://github.com/user-attachments/assets/0fe8b029-625e-4fb6-9e27-035cbd5ebaa1)

![image](https://github.com/user-attachments/assets/6133e3e3-5eaa-4058-b810-f6fbd7581013)


only downside is stil that they til today only support this crappy old outdated PFS groups :/

**Comment by flyersa** [comment]
anything else you want me to test?

**Comment by berendt** [comment]
> only downside is stil that they til today only support this crappy old outdated PFS groups :/

Can https://review.opendev.org/c/openstack/neutron-vpnaas/+/898830 help here?

**Comment by flyersa** [comment]
> > only downside is stil that they til today only support this crappy old outdated PFS groups :/
> 
> Can https://review.opendev.org/c/openstack/neutron-vpnaas/+/898830 help here?

Yes, im following this for a while. I see it got some traction this month again. If they ever decide to add it that will most likely solve it. I think they didnt add it because of some api changes or something which wasnt backwards compatible or something like that.

**Comment by maliblatt** [comment]
I want to give also some feedback on the VPNaaS:
It also works for me, I could establish an IPsec connection which was created via Horizon to an remote IPsec device.
With my old test environment I can not give any Infos about network throughput. I think as soon as we will have the first tagged pre release and we will deploy on our plusserver dev environment we can also give some details about performance etc.

beside that everything seems running smooth :-)

**Comment by flyersa** [comment]
I noticed some issue with magnum which may be by default in the images but breaks it.

apparently there is both, installed magnum-capi-helm  and magnum-cluster-api  but it should only be magnum-cluster-api. I think this are two different implementations of the magnum capi driver. the magnum-capi-helm one is the one from stackHPC which isnt really working very good. The other one is the one from Vexxhost which works.

Having both on the same time triggers funny behaviors that sometimes it uses one or the other. magnum-capi-helm as example requires kube_version set on images, the magnum-cluster-api does not. So sometimes it triggers errors, sometimes not.

Also delete will sometimes work and sometimes will not. I think we should only include magnum-cluster-api and skip the helm one

**Comment by flyersa** [comment]
Thank you @berendt .

There is stil one issue with magnum now with SQLalchemy which is being adressed right now, maybe there is a fix available before release later.

https://bugs.launchpad.net/magnum/+bug/2067345

**Comment by flyersa** [comment]
Attached is also a simple upgrade script which reads which services are installed including fixed ones and ovn check which does a upgrade with all steps asking for retry/continue.

`#!/bin/bash

# List of fixed services (new services added at the top)
fixed_services=(
  "openstackclient"
  "common"
  "loadbalancer"
  "memcached"
  "redis"
  "rabbitmq"
  "mariadb"
  "opensearch"
  "prometheus"
  "grafana"
  "openvswitch"
  "cinder"
  "placement"
  "nova"
)

# MariaDB recovery flag and continue-at service
recover_mariadb=false
continue_at=""
skip_services=()
only_service=""
pull_only=false
dry_run=false

# Function to display help
display_help() {
  echo "Usage: $0 [options]"
  echo
  echo "Options:"
  echo "  --skip SERVICE            Skip the specified service(s)"
  echo "  --recover-mariadb         Recover MariaDB, useful if only 2 controllers are present"
  echo "  --continue-at SERVICE     Start at the specified service, skipping all before it"
  echo "  --show-active-services    List current active services in your cloud"
  echo "  --only SERVICE            Only run the specified service"
  echo "  --pull-only               Only pull the specified service(s)"
  echo "  --dry-run                 Show the commands that would be executed without running them"
  echo "  --help                    Display this help message"
  echo
}

# Function to show active services
show_active_services() {
  echo "Current active services in your cloud:"
  for service in "${fixed_services[@]}"; do
    echo "  - $service"
  done
  for service in "${filtered_dynamic_services[@]}"; do
    echo "  - $service"
  done
}

# Parse command line arguments to get skipped services, recovery flag, continue-at service, show-active-services, pull-only, and dry-run flags
show_active=false
while [[ $# -gt 0 ]]; do
  case $1 in
    --skip)
      skip_services+=("$2")
      shift
      shift
      ;;
    --recover-mariadb)
      recover_mariadb=true
      shift
      ;;
    --continue-at)
      continue_at="$2"
      shift
      shift
      ;;
    --show-active-services)
      show_active=true
      shift
      ;;
    --only)
      only_service="$2"
      shift
      shift
      ;;
    --pull-only)
      pull_only=true
      shift
      ;;
    --dry-run)
      dry_run=true
      shift
      ;;
    --help)
      display_help
      exit 0
      ;;
    *)
      shift
      ;;
  esac
done

# Fetch dynamic services
dynamic_services=($(openstack --os-cloud admin service list -f value -c Name))

# Remove specific services and adjust names
filtered_dynamic_services=()
for service in "${dynamic_services[@]}"; do
  service=$(echo "$service" | xargs)  # Trim whitespace
  if [[ "$service" == *"nova_legacy"* ]]; then
    continue
  fi
  if [[ "$service" == *"heat-cfn"* ]]; then
    continue
  fi
  if [[ "$service" == *"swift"* ]]; then
    continue
  fi
  if [[ "$service" == *"cinderv3"* ]]; then
    continue
  fi

  if [[ "$service" == "nova_legacy" ]] || [[ "$service" == "heat-cfn" ]] || [[ "$service" == "swift" ]] || [[ "$service" == "cinderv3" ]]; then
    continue
  elif [[ "$service" == "cinderv3" ]]; then
    if [[ ! " ${filtered_dynamic_services[@]} " =~ " cinder " ]]; then
      filtered_dynamic_services+=("cinder")
    fi
  else
    filtered_dynamic_services+=("$service")
  fi
done

# Combine fixed and dynamic services
all_services=("${fixed_services[@]}" "${filtered_dynamic_services[@]}")

# If show-active-services is set, display the active services and exit
if [ "$show_active" = true ]; then
  show_active_services
  exit 0
fi

# Function to check if a service should be skipped
should_skip() {
  local service=$1
  for skip in "${skip_services[@]}"; do
    if [ "$service" == "$skip" ]; then
      return 0
    fi
  done
  return 1
}

# Function to execute the command and handle errors
execute_service() {
  local service=$1
  if [ "$dry_run" = true ]; then
    echo "Dry-run: osism apply -a upgrade $service"
  else
    echo "Running Upgrade for $service"
    osism apply -a upgrade "$service"
    return_code=$?
    
    if [ $return_code -ne 0 ]; then
      echo "The service $service returned a failure, do you want to retry or continue with the next service? (r = retry, c = continue)"
      read -r choice
      if [ "$choice" == "r" ]; then
        execute_service "$service"
      elif [ "$choice" != "c" ]; then
        echo "Invalid option. Continuing to the next service."
      fi
    fi
  fi
}

# Function to pull the service
pull_service() {
  local service=$1
  if [ "$dry_run" = true ]; then
    echo "Dry-run: osism apply -a pull $service"
  else
    echo "Pulling $service"
    osism apply -a pull "$service"
  fi
}

# If only_service is set, run only that service and exit
if [ -n "$only_service" ]; then
  if [ "$pull_only" = true ]; then
    pull_service "$only_service"
  else
    execute_service "$only_service"
  fi
  exit 0
fi

# If pull_only is set, pull all services and exit
if [ "$pull_only" = true ]; then
  for service in "${all_services[@]}"; do
    if should_skip "$service"; then
      echo "Skipping $service"
      continue
    fi
    pull_service "$service"
  done
  exit 0
fi

# Check if we should start from a specific service
start_index=0
if [ -n "$continue_at" ]; then
  for i in "${!all_services[@]}"; do
    if [ "${all_services[$i]}" == "$continue_at" ]; then
      start_index=$i
      break
    fi
  done
fi

# Loop through each service and execute the command if not skipped, starting at the continue-at index
for ((i = start_index; i < ${#all_services[@]}; i++)); do
  service="${all_services[$i]}"
  if should_skip "$service"; then
    echo "Skipping $service"
    continue
  fi
  execute_service "$service"
  
  # If the current service is openvswitch, check for OVN agents and run ovn upgrade if present
  if [ "$service" == "openvswitch" ]; then
    if openstack --os-cloud admin network agent list | grep -q ovn; then
      echo "OVN agents detected, running OVN upgrade next"
      execute_service "ovn"
    fi
  fi
  
  # If the current service is mariadb and recover_mariadb is set, execute mariadb_recovery
  if [ "$service" == "mariadb" ] && [ "$recover_mariadb" = true ]; then
    execute_service "mariadb_recovery"
  fi
done

# If recover_mariadb is set and mariadb was skipped, execute mariadb_recovery at the end
if [ "$recover_mariadb" = true ]; then
  if ! should_skip "mariadb"; then
    execute_service "mariadb_recovery"
  fi
fi
`

`#!/bin/bash

# List of fixed services (new services added at the top)
fixed_services=(
  "openstackclient"
  "common"
  "loadbalancer"
  "memcached"
  "redis"
  "rabbitmq"
  "mariadb"
  "opensearch"
  "prometheus"
  "grafana"
  "openvswitch"
  "cinder"
  "placement"
  "nova"
)

# MariaDB recovery flag and continue-at service
recover_mariadb=false
continue_at=""
skip_services=()
only_service=""
pull_only=false
dry_run=false

# Function to display help
display_help() {
  echo "Usage: $0 [options]"
  echo
  echo "Options:"
  echo "  --skip SERVICE            Skip the specified service(s)"
  echo "  --recover-mariadb         Recover MariaDB, useful if only 2 controllers are present"
  echo "  --continue-at SERVICE     Start at the specified service, skipping all before it"
  echo "  --show-active-services    List current active services in your cloud"
  echo "  --only SERVICE            Only run the specified service"
  echo "  --pull-only               Only pull the specified service(s)"
  echo "  --dry-run                 Show the commands that would be executed without running them"
  echo "  --help                    Display this help message"
  echo
}

# Function to show active services
show_active_services() {
  echo "Current active services in your cloud:"
  for service in "${fixed_services[@]}"; do
    echo "  - $service"
  done
  for service in "${filtered_dynamic_services[@]}"; do
    echo "  - $service"
  done
}

# Parse command line arguments to get skipped services, recovery flag, continue-at service, show-active-services, pull-only, and dry-run flags
show_active=false
while [[ $# -gt 0 ]]; do
  case $1 in
    --skip)
      skip_services+=("$2")
      shift
      shift
      ;;
    --recover-mariadb)
      recover_mariadb=true
      shift
      ;;
    --continue-at)
      continue_at="$2"
      shift
      shift
      ;;
    --show-active-services)
      show_active=true
      shift
      ;;
    --only)
      only_service="$2"
      shift
      shift
      ;;
    --pull-only)
      pull_only=true
      shift
      ;;
    --dry-run)
      dry_run=true
      shift
      ;;
    --help)
      display_help
      exit 0
      ;;
    *)
      shift
      ;;
  esac
done

# Fetch dynamic services
dynamic_services=($(openstack --os-cloud admin service list -f value -c Name))

# Remove specific services and adjust names
filtered_dynamic_services=()
for service in "${dynamic_services[@]}"; do
  service=$(echo "$service" | xargs)  # Trim whitespace
  if [[ "$service" == *"nova_legacy"* ]]; then
    continue
  fi
  if [[ "$service" == *"heat-cfn"* ]]; then
    continue
  fi
  if [[ "$service" == *"swift"* ]]; then
    continue
  fi
  if [[ "$service" == *"cinderv3"* ]]; then
    continue
  fi

  if [[ "$service" == "nova_legacy" ]] || [[ "$service" == "heat-cfn" ]] || [[ "$service" == "swift" ]] || [[ "$service" == "cinderv3" ]]; then
    continue
  elif [[ "$service" == "cinderv3" ]]; then
    if [[ ! " ${filtered_dynamic_services[@]} " =~ " cinder " ]]; then
      filtered_dynamic_services+=("cinder")
    fi
  else
    filtered_dynamic_services+=("$service")
  fi
done

# Combine fixed and dynamic services
all_services=("${fixed_services[@]}" "${filtered_dynamic_services[@]}")

# If show-active-services is set, display the active services and exit
if [ "$show_active" = true ]; then
  show_active_services
  exit 0
fi

# Function to check if a service should be skipped
should_skip() {
  local service=$1
  for skip in "${skip_services[@]}"; do
    if [ "$service" == "$skip" ]; then
      return 0
    fi
  done
  return 1
}

# Function to execute the command and handle errors
execute_service() {
  local service=$1
  if [ "$dry_run" = true ]; then
    echo "Dry-run: osism apply -a upgrade $service"
  else
    echo "Running Upgrade for $service"
    osism apply -a upgrade "$service"
    return_code=$?
    
    if [ $return_code -ne 0 ]; then
      echo "The service $service returned a failure, do you want to retry or continue with the next service? (r = retry, c = continue)"
      read -r choice
      if [ "$choice" == "r" ]; then
        execute_service "$service"
      elif [ "$choice" != "c" ]; then
        echo "Invalid option. Continuing to the next service."
      fi
    fi
  fi
}

# Function to pull the service
pull_service() {
  local service=$1
  if [ "$dry_run" = true ]; then
    echo "Dry-run: osism apply -a pull $service"
  else
    echo "Pulling $service"
    osism apply -a pull "$service"
  fi
}

# If only_service is set, run only that service and exit
if [ -n "$only_service" ]; then
  if [ "$pull_only" = true ]; then
    pull_service "$only_service"
  else
    execute_service "$only_service"
  fi
  exit 0
fi

# If pull_only is set, pull all services and exit
if [ "$pull_only" = true ]; then
  for service in "${all_services[@]}"; do
    if should_skip "$service"; then
      echo "Skipping $service"
      continue
    fi
    pull_service "$service"
  done
  exit 0
fi

# Check if we should start from a specific service
start_index=0
if [ -n "$continue_at" ]; then
  for i in "${!all_services[@]}"; do
    if [ "${all_services[$i]}" == "$continue_at" ]; then
      start_index=$i
      break
    fi
  done
fi

# Loop through each service and execute the command if not skipped, starting at the continue-at index
for ((i = start_index; i < ${#all_services[@]}; i++)); do
  service="${all_services[$i]}"
  if should_skip "$service"; then
    echo "Skipping $service"
    continue
  fi
  execute_service "$service"
  
  # If the current service is openvswitch, check for OVN agents and run ovn upgrade if present
  if [ "$service" == "openvswitch" ]; then
    if openstack --os-cloud admin network agent list | grep -q ovn; then
      echo "OVN agents detected, running OVN upgrade next"
      execute_service "ovn"
    fi
  fi
  
  # If the current service is mariadb and recover_mariadb is set, execute mariadb_recovery
  if [ "$service" == "mariadb" ] && [ "$recover_mariadb" = true ]; then
    execute_service "mariadb_recovery"
  fi
done

# If recover_mariadb is set and mariadb was skipped, execute mariadb_recovery at the end
if [ "$recover_mariadb" = true ]; then
  if ! should_skip "mariadb"; then
    execute_service "mariadb_recovery"
  fi
fi
`

**Comment by flyersa** [comment]
btw there are again newer capi drivers from vexxhost available. Way to go should be to include the "latest" available when building the images.

We have Magnum rolled out now on multiple customers with manual fixes on 2023.2 and it works very good.

**Comment by berendt** [comment]
> btw there are again newer capi drivers from vexxhost available. Way to go should be to include the "latest" available when building the images.
> 
> We have Magnum rolled out now on multiple customers with manual fixes on 2023.2 and it works very good.

We install the latest available magnum-cluster-api package from Pypi in the latest 2023.2/204.1 Magnum container images. Those images are rebuild every night at the moment. I think the problem is that no never release is available @ Pypi: https://pypi.org/project/magnum-cluster-api/. Lastest release from 19. July 2024 there. I would prefer to not install/use the main branch from https://github.com/vexxhost/magnum-cluster-api.

```
{% set magnum_base_additional_pip_packages = [ 'magnum-cluster-api' ] %}
```

**Comment by berendt** [comment]
* https://github.com/osism/release/issues/1540

**Comment by amiremami98** [comment]
> I can confirm with the backport OVN VPNaaS works.
> 
> ![image](https://github.com/user-attachments/assets/d94bed92-475b-47ed-969c-b66902d7f942)
> 
> ![image](https://github.com/user-attachments/assets/9c82c6f1-7a33-48a5-bba9-4541bc5d592b)
> 
> ![image](https://github.com/user-attachments/assets/0fe8b029-625e-4fb6-9e27-035cbd5ebaa1)
> 
> ![image](https://github.com/user-attachments/assets/6133e3e3-5eaa-4058-b810-f6fbd7581013)
> 
> only downside is stil that they til today only support this crappy old outdated PFS groups :/

I've followed the instructions below but couldn't find neutron_ovn_vpn_agent docker image?
https://review.opendev.org/c/openstack/kolla-ansible/+/924575

**Comment by berendt** [comment]
> I've followed the instructions below but couldn't find neutron_ovn_vpn_agent docker image? https://review.opendev.org/c/openstack/kolla-ansible/+/924575

The neutron-ovn-vpn-agent image is here: https://quay.io/repository/osism/neutron-ovn-vpn-agent?tab=tags

**Comment by amiremami98** [comment]
> The neutron-ovn-vpn-agent image is here: https://quay.io/repository/osism/neutron-ovn-vpn-agent?tab=tags

Thanks, But I'm using Rocky-9 and 2024.1 version.
Guess We should make one.

**Comment by amiremami98** [comment]
> > I've followed the instructions below but couldn't find neutron_ovn_vpn_agent docker image? https://review.opendev.org/c/openstack/kolla-ansible/+/924575
> 
> The neutron-ovn-vpn-agent image is here: https://quay.io/repository/osism/neutron-ovn-vpn-agent?tab=tags

It worked for rocky-9 too.
Thanks.

**Comment by berendt** [comment]
> > The neutron-ovn-vpn-agent image is here: https://quay.io/repository/osism/neutron-ovn-vpn-agent?tab=tags
> 
> It worked for rocky-9 too. Thanks.

Thanks for the update. The "old outdated PFS groups" topic is also moving forward. We initiated a neutron-lib release two days ago that is a dependency of the change in VPNaaS for OVN.

**Comment by Erick-shi** [comment]
hi, my problem is not ovn, I have three controller node, and have three memcached service , I found when I stop one memcached service, my cluster is error.   I use kolla-ansible deploy my cluster, why  memcached not be loadbanlence ?

**Comment by berendt** [comment]
> hi, my problem is not ovn, I have three controller node, and have three memcached service , I found when I stop one memcached service, my cluster is error. I use kolla-ansible deploy my cluster, why memcached not be loadbanlence ?

Please continue in osism/issues#1230. This issue here is closed. Memcached has always been standalone on every control node and was never loadbalanced.
