### ISSUE TITLE
[bug] CiaB Installation fails because of netbox process status

### ISSUE THREAD

**Issue by scoopex** [osism/issues#1136]
### OSISM release version

8.0.0

### What's the problem?

I performed a complete reinstall of CiaB and it fails in the "bootstrap" phase.

According to /var/log/install-cloud-in-a-box.log it fails in the following step:
```
....
bootstrap | TASK [osism.services.netbox : Flush handlers] **********************************
bootstrap | 
bootstrap | RUNNING HANDLER [osism.services.netbox : Restart netbox service] ***************
bootstrap | skipping: [manager.systems.in-a-box.cloud]
bootstrap | 
bootstrap | RUNNING HANDLER [osism.services.netbox : Wait for netbox service to start] *****
bootstrap | Pausing for 60 seconds
bootstrap | changed: [manager.systems.in-a-box.cloud]
bootstrap | 
bootstrap | RUNNING HANDLER [osism.services.netbox : Wait for an healthy netbox service] ***
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (60 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (59 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (58 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (57 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (56 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (55 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (54 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (53 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (52 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (51 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (50 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (49 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (48 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (47 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (46 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (45 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (44 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (43 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (42 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (41 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (40 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (39 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (38 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (37 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (36 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (35 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (34 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (33 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (32 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (31 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (30 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (29 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (28 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (27 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (26 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (25 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (24 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (23 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (22 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (21 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (20 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (19 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (18 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (17 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (16 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (15 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (14 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (13 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (12 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (11 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (10 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (9 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (8 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (7 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (6 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (5 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (4 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (3 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (2 retries left).
bootstrap | FAILED - RETRYING: [manager.systems.in-a-box.cloud]: Wait for an healthy netbox service (1 retries left).
bootstrap | fatal: [manager.systems.in-a-box.cloud]: FAILED! => {"attempts": 60, "changed": true, "cmd": "set -o pipefail\ndocker compose --project-directory /opt/trap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | W: Tried to start delayed item http://security.ubuntu.com/ubuntu jammy-security InRelease, but failed
bootstrap | + ./run.sh bootstrap
bootstrap | + chmod o+rw /var/run/docker.sock
bootstrap | + ./run.sh configuration
bootstrap | + find /opt/configuration -type f -exec sed -i s/eno1/eno1np0/g '{}' +
bootstrap | + [[ sandbox == \s\a\n\d\b\o\x ]]
bootstrap | + ./run.sh netbox
bootstrap | + set +x
netbox    ps --all --format json |    jq '. | select(.State==\"created\" or .State==\"exited\" or .Health==\"starting\" or .Health==\"unhealthy\") | .Name'\n", "delta": "0:00:00.071169", "end": "2024-09-18 07:59:41.448533", "msg": "", "rc": 0, "start": "2024-09-18 07:59:41.377364", "stderr": "", "stderr_lines": [], "stdout": "\"netbox-netbox-1\"\n\"netbox-netbox-worker-1\"", "stdout_lines": ["\"netbox-netbox-1\"", "\"netbox-netbox-worker-1\""]}
bootstrap | 
bootstrap | PLAY RECAP *********************************************************************
bootstrap | manager.systems.in-a-box.cloud : ok=27   changed=17   unreachable=0    failed=1    skipped=3    rescued=0    ignored=0   
```

### References to existing reports

https://github.com/osism/issues/issues/1135

### Severity

low

### Urgency

low

**Comment by scoopex** [comment]
I manually executed he docker compose and i receive the following output:

```
[+] Running 3/0
 ✔ Container netbox-redis-1     Running                                                                                                                             0.0s 
 ✔ Container netbox-postgres-1  Running                                                                                                                             0.0s 
 ✔ Container netbox-netbox-1    Running                                                                                                                             0.0s 
Attaching to netbox-1, netbox-worker-1, postgres-1, redis-1
netbox-1         | django.core.exceptions.ImproperlyConfigured: Plugin netbox_bgp requires NetBox maximum version 4.0.99 (current: 4.1.0).
netbox-1         | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-1         | ⏳ Waiting on DB... (18s / 90s)
netbox-1         | django.core.exceptions.ImproperlyConfigured: Plugin netbox_bgp requires NetBox maximum version 4.0.99 (current: 4.1.0).
netbox-1         | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-1         | ⏳ Waiting on DB... (21s / 90s)
...
netbox-1         | django.core.exceptions.ImproperlyConfigured: Plugin netbox_bgp requires NetBox maximum version 4.0.99 (current: 4.1.0).
netbox-1         | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-1         | ⏳ Waiting on DB... (84s / 90s)
netbox-1         | django.core.exceptions.ImproperlyConfigured: Plugin netbox_bgp requires NetBox maximum version 4.0.99 (current: 4.1.0).
netbox-1         | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox-1         | ⏳ Waiting on DB... (87s / 90s)
netbox-1         | ❌ Waited 90s or more for the DB to become ready.
Gracefully stopping... (press Ctrl+C again to force)
dependency failed to start: container netbox-netbox-1 is unhealthy
....
```

**Comment by kayamax** [comment]
I have changed in environments/manager/images.yml:13:netbox_tag: "v4.0.11" to come over it so I faced the next bug:

nova-compute-ironic is infinitely in restarting state:
`d9cd9250770b   quay.io/osism/nova-compute-ironic:29.2.1.20240909      "dumb-init --single-…"   15 hours ago   Up 3 seconds (health: starting)                                                                                        nova_compute_ironic`

and here portion of /var/lib/docker/volumes/kolla_logs/_data/nova/nova-compute-ironic.log:
```
2024-09-17 16:32:36.344 7 INFO os_vif [-] Loaded VIF plugins: linux_bridge, noop, ovs
2024-09-17 16:32:36.443 7 INFO oslo_messaging._drivers.amqpdriver [None req-2d6ff09c-c350-4de4-a662-2b1459875be4 - - - - - -] Creating reply queue: reply_e9e802a52e284523a9d30aecae36234e
2024-09-17 16:32:36.456 7 INFO oslo_messaging._drivers.amqpdriver [None req-2d6ff09c-c350-4de4-a662-2b1459875be4 - - - - - -] Expecting reply to msg a699c249fd934bd8b34569ae8789d3d2 in queue reply_e9e802a52e284523a9d30aecae36234e
2024-09-17 16:32:36.469 7 INFO oslo_messaging._drivers.amqpdriver [-] Received RPC response for msg a699c249fd934bd8b34569ae8789d3d2
2024-09-17 16:32:37.143 7 INFO nova.virt.driver [None req-2d6ff09c-c350-4de4-a662-2b1459875be4 - - - - - -] Loading compute driver 'ironic.IronicDriver'
2024-09-17 16:32:37.152 7 INFO nova.compute.provider_config [None req-2d6ff09c-c350-4de4-a662-2b1459875be4 - - - - - -] No provider configs found in /etc/nova/provider_config/. If files are present, ensure the Nova process has access.
2024-09-17 16:32:37.153 7 INFO oslo_messaging._drivers.amqpdriver [None req-2d6ff09c-c350-4de4-a662-2b1459875be4 - - - - - -] Expecting reply to msg 9f7df52308464970a8825e1d1bdb30b5 in queue reply_e9e802a52e284523a9d30aecae36234e
2024-09-17 16:32:37.162 7 INFO oslo_messaging._drivers.amqpdriver [-] Received RPC response for msg 9f7df52308464970a8825e1d1bdb30b5
2024-09-17 16:32:37.170 7 WARNING oslo_config.cfg [None req-2d6ff09c-c350-4de4-a662-2b1459875be4 - - - - - -] Deprecated: Option "api_servers" from group "glance" is deprecated for removal (
Support for image service configuration via standard keystoneauth1 Adapter
options was added in the 17.0.0 Queens release. The api_servers option was
retained temporarily to allow consumers time to cut over to a real load
balancing solution.
).  Its value may be silently ignored in the future.
2024-09-17 16:32:37.186 7 INFO nova.service [-] Starting compute node (version 29.2.1)
2024-09-17 16:32:37.187 7 INFO oslo_messaging._drivers.amqpdriver [None req-1b66f9ea-bf40-44e1-99c1-662981b63e8a - - - - - -] Expecting reply to msg ef8a10b5bcdd4f3ca967b8664a32e8f6 in queue reply_e9e802a52e284523a9d30aecae36234e
2024-09-17 16:32:37.199 7 INFO oslo_messaging._drivers.amqpdriver [-] Received RPC response for msg ef8a10b5bcdd4f3ca967b8664a32e8f6
2024-09-17 16:32:37.200 7 INFO oslo_messaging._drivers.amqpdriver [None req-1b66f9ea-bf40-44e1-99c1-662981b63e8a - - - - - -] Expecting reply to msg 4af0e9418f35417e9dfd4856b6208be2 in queue reply_e9e802a52e284523a9d30aecae36234e
2024-09-17 16:32:37.215 7 INFO oslo_messaging._drivers.amqpdriver [-] Received RPC response for msg 4af0e9418f35417e9dfd4856b6208be2
2024-09-17 16:32:37.340 7 ERROR nova.virt.ironic.driver [None req-1b66f9ea-bf40-44e1-99c1-662981b63e8a - - - - - -] An unknown error has occurred when trying to get the list of nodes from the Ironic inventory. Error: The request you have made requires authentication. (HTTP 401) (Request-ID: req-5b05bc70-d112-4ffb-8f2b-3f691c9eebea): keystoneauth1.exceptions.http.Unauthorized: The request you have made requires authentication. (HTTP 401) (Request-ID: req-5b05bc70-d112-4ffb-8f2b-3f691c9eebea)
2024-09-17 16:32:37.340 7 ERROR oslo_service.service [None req-1b66f9ea-bf40-44e1-99c1-662981b63e8a - - - - - -] Error starting thread.: nova.exception.VirtDriverNotReady: Virt driver is not ready.
2024-09-17 16:32:37.340 7 ERROR oslo_service.service Traceback (most recent call last):
2024-09-17 16:32:37.340 7 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.10/site-packages/nova/virt/ironic/driver.py", line 614, in _get_node_list
2024-09-17 16:32:37.340 7 ERROR oslo_service.service     node_generator = self.ironic_connection.nodes(**kwargs)
2024-09-17 16:32:37.340 7 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.10/site-packages/nova/virt/ironic/driver.py", line 199, in ironic_connection
```
