### ISSUE TITLE
[bug] CIAB 8.0.0 Opensearch Dashboard @https://api.in-a-box.cloud:5601 hangs 

### ISSUE THREAD

**Issue by kayamax** [osism/issues#1143]
### OSISM release version

8.0.0

### What's the problem?

docker logs -f  opensearch_dashboards:
```
[agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
Index Management - CommonService - apiCaller StatusCodeError: no handler found for uri [/_plugins/_security/api/account] and method [GET]
    at respond (/usr/share/opensearch-dashboards/node_modules/elasticsearch/src/lib/transport.js:349:15)
    at checkRespForFailure (/usr/share/opensearch-dashboards/node_modules/elasticsearch/src/lib/transport.js:306:7)
    at HttpConnector.<anonymous> (/usr/share/opensearch-dashboards/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
    at IncomingMessage.wrapper (/usr/share/opensearch-dashboards/node_modules/lodash/lodash.js:4991:19)
    at IncomingMessage.emit (node:events:529:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  status: 400,
  displayName: 'BadRequest',
  path: '/_plugins/_security/api/account',
  query: undefined,
  body: {
    error: 'no handler found for uri [/_plugins/_security/api/account] and method [GET]'
  },
  statusCode: 400,
  response: '{"error":"no handler found for uri [/_plugins/_security/api/account] and method [GET]"}',
  toString: [Function (anonymous)],
  toJSON: [Function (anonymous)]
}
[agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
```

### References to existing reports

References to existing bug reports, mailing lists, ...

### Severity

low

### Urgency

low

**Comment by berendt** [comment]
Openserach itself works?

**Comment by kayamax** [comment]
```
root@manager:/home/dragon# curl -XGET "http://192.168.16.10:9200/_cluster/health" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   463  100   463    0     0   263k      0 --:--:-- --:--:-- --:--:--  452k
{
  "cluster_name": "kolla_logging",
  "status": "yellow",
  "timed_out": false,
  "number_of_nodes": 1,
  "number_of_data_nodes": 1,
  "discovered_master": true,
  "discovered_cluster_manager": true,
  "active_primary_shards": 14,
  "active_shards": 14,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 9,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 60.86956521739131
}
```

**Comment by berendt** [comment]
Outdated. If it is still relevant with current versions, please reopen.
