### ISSUE TITLE
kolla-ansible: MarkupSafe >= 3.0.0 not working

### ISSUE THREAD

**Issue by janhorstmann** [osism/issues#1161]
### OSISM release version

latest

### What's the problem?

Deployment of OpenStack fails during templating of service loadbalancer configurations (e.g.: [1]).

It is caused  by the [`3.0.0` release](https://github.com/pallets/markupsafe/releases/tag/3.0.0) of the [MarkupSafe package](https://github.com/pallets/markupsafe).

As a workaround MarkupSafe can be downgraded to a version `<3.0.0`

[1]
```
TASK [haproxy-config : Copying over barbican haproxy config] *****************************************************************
task path: /ansible/roles/haproxy-config/tasks/main.yml:2
Wednesday 09 October 2024  09:58:24 +0000 (0:00:01.732)       0:01:21.489 *****
<192.168.16.10> ESTABLISH SSH CONNECTION FOR USER: dragon
<192.168.16.10> SSH: EXEC ssh -vvv -o ControlMaster=auto -o ControlPersist=1800s -o StrictHostKeyChecking=no -o 'IdentityFile="/ansible/secrets/id_rsa.operator"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="dragon"' -o ConnectTimeout=60 -o 'ControlPath="/root/.ansible/cp/951ac3ac20"' 192.168.16.10 '/bin/sh -c '"'"'echo ~dragon && sleep 0'"'"''
<192.168.16.10> (0, b'/home/dragon\n', b"OpenSSH_9.2p1 Debian-2+deb12u3, OpenSSL 3.0.14 4 Jun 2024\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 192.168.16.10 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/root/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/root/.ssh/known_hosts2'\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 17652\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n")
<192.168.16.10> ESTABLISH SSH CONNECTION FOR USER: dragon
<192.168.16.10> SSH: EXEC ssh -vvv -o ControlMaster=auto -o ControlPersist=1800s -o StrictHostKeyChecking=no -o 'IdentityFile="/ansible/secrets/id_rsa.operator"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="dragon"' -o ConnectTimeout=60 -o 'ControlPath="/root/.ansible/cp/951ac3ac20"' 192.168.16.10 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/dragon/.ansible/tmp `"&& mkdir "` echo /home/dragon/.ansible/tmp/ansible-tmp-1728467905.242355-18082-152773312142023 `" && echo ansible-tmp-1728467905.242355-18082-152773312142023="` echo /home/dragon/.ansible/tmp/ansible-tmp-1728467905.242355-18082-152773312142023 `" ) && sleep 0'"'"''
<192.168.16.10> (0, b'ansible-tmp-1728467905.242355-18082-152773312142023=/home/dragon/.ansible/tmp/ansible-tmp-1728467905.242355-18082-152773312142023\n', b"OpenSSH_9.2p1 Debian-2+deb12u3, OpenSSL 3.0.14 4 Jun 2024\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 192.168.16.10 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/root/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/root/.ssh/known_hosts2'\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 17652\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n")
<192.168.16.10> ESTABLISH SSH CONNECTION FOR USER: dragon
<192.168.16.10> SSH: EXEC ssh -vvv -o ControlMaster=auto -o ControlPersist=1800s -o StrictHostKeyChecking=no -o 'IdentityFile="/ansible/secrets/id_rsa.operator"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="dragon"' -o ConnectTimeout=60 -o 'ControlPath="/root/.ansible/cp/951ac3ac20"' 192.168.16.10 '/bin/sh -c '"'"'rm -f -r /home/dragon/.ansible/tmp/ansible-tmp-1728467905.242355-18082-152773312142023/ > /dev/null 2>&1 && sleep 0'"'"''
<192.168.16.10> (0, b'', b"OpenSSH_9.2p1 Debian-2+deb12u3, OpenSSL 3.0.14 4 Jun 2024\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 192.168.16.10 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/root/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/root/.ssh/known_hosts2'\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 17652\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n")
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/ansible/plugins/action/template.py", line 151, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False, overrides=overrides)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ansible/template/__init__.py", line 993, in do_template
    res = myenv.concat(rf)
          ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ansible/template/native_helpers.py", line 81, in ansible_concat
    return ''.join([to_text(v) for v in nodes])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ansible/template/native_helpers.py", line 81, in <listcomp>
    return ''.join([to_text(v) for v in nodes])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 436, in root
  File "/usr/local/lib/python3.11/site-packages/ansible/template/__init__.py", line 364, in call
    return super().call(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/runtime.py", line 303, in call
    return __obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/runtime.py", line 768, in __call__
    return self._invoke(arguments, autoescape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 193, in macro
  File "/usr/local/lib/python3.11/site-packages/ansible/template/__init__.py", line 294, in wrapper
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/filters.py", line 1030, in do_format
    return soft_str(value) % (kwargs or args)
           ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
  File "/usr/local/lib/python3.11/site-packages/markupsafe/__init__.py", line 165, in __mod__
    return self.__class__(super().__mod__(value))
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/markupsafe/__init__.py", line 370, in __str__
    return str(self.escape(self.obj))
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/markupsafe/__init__.py", line 235, in escape
    rv = escape(s)
         ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/markupsafe/__init__.py", line 45, in escape
    return Markup(_escape_inner(str(s)))
                  ^^^^^^^^^^^^^^^^^^^^^
SystemError: <built-in function _escape_inner> returned NULL without setting an exception
failed: [testbed-node-0.testbed.osism.xyz] (item={'key': 'barbican-api', 'value': {'container_name': 'barbican_api', 'group': 'barbican-api', 'enabled': True, 'environment': {'CS_AUTH_KEYS': ''}, 'image': 'nexus.testbed.osism.xyz:8192/osism/barbican-api:2024.1', 'volumes': ['/etc/kolla/barbican-api/:/var/lib/kolla/config_files/:ro', '/etc/localtime:/etc/localtime:ro', '/etc/timezone:/etc/timezone:ro', 'barbican:/var/lib/barbican/', 'kolla_logs:/var/log/kolla/', ''], 'dimensions': {}, 'healthcheck': {'interval': '30', 'retries': '3', 'start_period': '5', 'test': ['CMD-SHELL', 'healthcheck_curl http://192.168.16.10:9311'], 'timeout': '30'}, 'haproxy': {'barbican_api': {'enabled': 'yes', 'mode': 'http', 'external': False, 'port': '9311', 'listen_port': '9311', 'tls_backend': 'no'}, 'barbican_api_external': {'enabled': 'yes', 'mode': 'http', 'external': True, 'external_fqdn': 'api.testbed.osism.xyz', 'port': '9311', 'listen_port': '9311', 'tls_backend': 'no'}}}}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "key": "barbican-api",
        "value": {
            "container_name": "barbican_api",
            "dimensions": {},
            "enabled": true,
            "environment": {
                "CS_AUTH_KEYS": ""
            },
            "group": "barbican-api",
            "haproxy": {
                "barbican_api": {
                    "enabled": "yes",
                    "external": false,
                    "listen_port": "9311",
                    "mode": "http",
                    "port": "9311",
                    "tls_backend": "no"
                },
                "barbican_api_external": {
                    "enabled": "yes",
                    "external": true,
                    "external_fqdn": "api.testbed.osism.xyz",
                    "listen_port": "9311",
                    "mode": "http",
                    "port": "9311",
                    "tls_backend": "no"
                }
            },
            "healthcheck": {
                "interval": "30",
                "retries": "3",
                "start_period": "5",
                "test": [
                    "CMD-SHELL",
                    "healthcheck_curl http://192.168.16.10:9311"
                ],
                "timeout": "30"
            },
            "image": "nexus.testbed.osism.xyz:8192/osism/barbican-api:2024.1",
            "volumes": [
                "/etc/kolla/barbican-api/:/var/lib/kolla/config_files/:ro",
                "/etc/localtime:/etc/localtime:ro",
                "/etc/timezone:/etc/timezone:ro",
                "barbican:/var/lib/barbican/",
                "kolla_logs:/var/log/kolla/",
                ""
            ]
        }
    },
    "msg": "SystemError: <built-in function _escape_inner> returned NULL without setting an exception"
}
```

### References to existing reports

References to existing bug reports, mailing lists, ...

### Severity

high

### Urgency

high

**Comment by janhorstmann** [comment]
I can no longer observe the issue with `MarkupSafe==3.0.2`. It seems to be fixed with https://github.com/pallets/markupsafe/issues/472
in [this release](https://github.com/pallets/markupsafe/releases/tag/3.0.2)
