### ISSUE TITLE
[bug] cinder : Task "Running Cinder bootstrap container" fails

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#1177]
### OSISM release version

8.0.2

### What's the problem?

Task fails during cinder upgrade on control node. We cannot find a specific error message in the output. If you have any idea...

msg:
```
Container exited with non-zero return code 1
```

stderr:
```
+ sudo -E kolla_set_configs
INFO:__main__:Loading config file at /var/lib/kolla/config_files/config.json
INFO:__main__:Validating config file
INFO:__main__:Kolla config strategy set to: COPY_ALWAYS
INFO:__main__:Copying service configuration files
INFO:__main__:Copying /var/lib/kolla/config_files/cinder.conf to /etc/cinder/cinder.conf
INFO:__main__:Setting permission for /etc/cinder/cinder.conf
INFO:__main__:Copying /var/lib/kolla/config_files/cinder-wsgi.conf to /etc/apache2/conf-enabled/cinder-wsgi.conf
INFO:__main__:Setting permission for /etc/apache2/conf-enabled/cinder-wsgi.conf
INFO:__main__:Writing out command to execute
INFO:__main__:Setting permission for /var/lib/cinder
INFO:__main__:Setting permission for /var/log/kolla/cinder
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log.6.gz
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log.5.gz
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-backup.log
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log.2.gz
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-volume.log.2.gz
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-volume.log
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log.4.gz
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log.2.gz
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log.5.gz
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-scheduler.log
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log.1
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-volume.log.1
INFO:__main__:Setting permission for /var/log/kolla/cinder/privsep-helper.log
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log.1
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log.1
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log.6.gz
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log.3.gz
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-volume.log.3.gz
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log.4.gz
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log.3.gz
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log.4.gz
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log.3.gz
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-access.log.5.gz
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api.log.6.gz
INFO:__main__:Setting permission for /var/log/kolla/cinder/cinder-api-error.log.2.gz
++ cat /run_command
+ CMD='/usr/sbin/apache2 -DFOREGROUND'
+ ARGS=
+ sudo kolla_copy_cacerts
rehash: warning: skipping ca-certificates.crt,it does not contain exactly one certificate or CRL
+ [[ ! -n '' ]]
+ . kolla_extend_start
++ [[ ! -d /var/log/kolla/cinder ]]
+++ stat -c %a /var/log/kolla/cinder
++ [[ 2755 != \7\5\5 ]]
++ chmod 755 /var/log/kolla/cinder
++ . /usr/local/bin/kolla_cinder_extend_start
+++ set -o errexit
+++ [[ -n 0 ]]
+++ cinder-manage db sync
```

stdout:
```
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
```

### References to existing reports

References to existing bug reports, mailing lists, .

### Severity

low

### Urgency

low

**Comment by Nils98Ar** [comment]
This seems to be the reason:
```
dragon@control01:~$ docker exec cinder_api bash -c "cinder-manage db sync; echo $?"
1
```

**Comment by Nils98Ar** [comment]
cinder-api.log:
```
2024-11-06 14:43:03.725 4259 INFO cinder.db.migration [-] Applying migration(s)
2024-11-06 14:43:03.727 4259 INFO alembic.runtime.migration [-] Context impl MySQLImpl.
2024-11-06 14:43:03.727 4259 INFO alembic.runtime.migration [-] Will assume non-transactional DDL.
2024-11-06 14:43:03.733 4259 CRITICAL cinder [-] Unhandled error: alembic.util.exc.CommandError: Can't locate revision identified by 'b8660621f1b9'
2024-11-06 14:43:03.733 4259 ERROR cinder Traceback (most recent call last):
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/alembic/script/base.py", line 233, in _catch_revision_errors
2024-11-06 14:43:03.733 4259 ERROR cinder     yield
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/alembic/script/base.py", line 443, in _upgrade_revs
2024-11-06 14:43:03.733 4259 ERROR cinder     for script in reversed(list(revs))
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/alembic/script/revision.py", line 797, in iterate_revisions
2024-11-06 14:43:03.733 4259 ERROR cinder     revisions, heads = fn(
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/alembic/script/revision.py", line 1452, in _collect_upgrade_revisions
2024-11-06 14:43:03.733 4259 ERROR cinder     current_revisions = self.get_revisions(lower)
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/alembic/script/revision.py", line 525, in get_revisions
2024-11-06 14:43:03.733 4259 ERROR cinder     return sum([self.get_revisions(id_elem) for id_elem in id_], ())
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/alembic/script/revision.py", line 525, in <listcomp>
2024-11-06 14:43:03.733 4259 ERROR cinder     return sum([self.get_revisions(id_elem) for id_elem in id_], ())
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/alembic/script/revision.py", line 550, in get_revisions
2024-11-06 14:43:03.733 4259 ERROR cinder     return tuple(
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/alembic/script/revision.py", line 551, in <genexpr>
2024-11-06 14:43:03.733 4259 ERROR cinder     self._revision_for_ident(rev_id, branch_label)
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/alembic/script/revision.py", line 622, in _revision_for_ident
2024-11-06 14:43:03.733 4259 ERROR cinder     raise ResolutionError(
2024-11-06 14:43:03.733 4259 ERROR cinder alembic.script.revision.ResolutionError: No such revision or branch 'b8660621f1b9'
2024-11-06 14:43:03.733 4259 ERROR cinder
2024-11-06 14:43:03.733 4259 ERROR cinder The above exception was the direct cause of the following exception:
2024-11-06 14:43:03.733 4259 ERROR cinder
2024-11-06 14:43:03.733 4259 ERROR cinder Traceback (most recent call last):
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/bin/cinder-manage", line 8, in <module>
2024-11-06 14:43:03.733 4259 ERROR cinder     sys.exit(main())
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/cinder/cmd/manage.py", line 1152, in main
2024-11-06 14:43:03.733 4259 ERROR cinder     fn(**fn_kwargs)
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/cinder/cmd/manage.py", line 191, in sync
2024-11-06 14:43:03.733 4259 ERROR cinder     db_migration.db_sync(version)
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/cinder/db/migration.py", line 103, in db_sync
2024-11-06 14:43:03.733 4259 ERROR cinder     _upgrade_alembic(engine, config, version)
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/cinder/db/migration.py", line 56, in _upgrade_alembic
2024-11-06 14:43:03.733 4259 ERROR cinder     alembic_api.upgrade(config, version or 'head')
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/alembic/command.py", line 378, in upgrade
2024-11-06 14:43:03.733 4259 ERROR cinder     script.run_env()
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/alembic/script/base.py", line 569, in run_env
2024-11-06 14:43:03.733 4259 ERROR cinder     util.load_python_file(self.dir, "env.py")
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
2024-11-06 14:43:03.733 4259 ERROR cinder     module = load_module_py(module_id, path)
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
2024-11-06 14:43:03.733 4259 ERROR cinder     spec.loader.exec_module(module)  # type: ignore
2024-11-06 14:43:03.733 4259 ERROR cinder   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-11-06 14:43:03.733 4259 ERROR cinder   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/cinder/db/migrations/env.py", line 100, in <module>
2024-11-06 14:43:03.733 4259 ERROR cinder     run_migrations_online()
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/cinder/db/migrations/env.py", line 94, in run_migrations_online
2024-11-06 14:43:03.733 4259 ERROR cinder     context.run_migrations()
2024-11-06 14:43:03.733 4259 ERROR cinder   File "<string>", line 8, in run_migrations
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/alembic/runtime/environment.py", line 867, in run_migrations
2024-11-06 14:43:03.733 4259 ERROR cinder     self.get_context().run_migrations(**kw)
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/alembic/runtime/migration.py", line 611, in run_migrations
2024-11-06 14:43:03.733 4259 ERROR cinder     for step in self._migrations_fn(heads, self):
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/alembic/command.py", line 367, in upgrade
2024-11-06 14:43:03.733 4259 ERROR cinder     return script._upgrade_revs(revision, rev)
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/alembic/script/base.py", line 431, in _upgrade_revs
2024-11-06 14:43:03.733 4259 ERROR cinder     with self._catch_revision_errors(
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
2024-11-06 14:43:03.733 4259 ERROR cinder     self.gen.throw(typ, value, traceback)
2024-11-06 14:43:03.733 4259 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/alembic/script/base.py", line 265, in _catch_revision_errors
2024-11-06 14:43:03.733 4259 ERROR cinder     raise util.CommandError(resolution) from re
2024-11-06 14:43:03.733 4259 ERROR cinder alembic.util.exc.CommandError: Can't locate revision identified by 'b8660621f1b9'
2024-11-06 14:43:03.733 4259 ERROR cinder
```

**Comment by Nils98Ar** [comment]
```
2024-11-06 13:56:37.493 1007 CRITICAL cinder [-] Unhandled error: oslo_db.exception.DBDataError: (pymysql.err.DataError) (1265, "Data truncated for column 'use_quota' at row 216")
(Background on this error at: https://sqlalche.me/e/14/9h9h)
```

**Comment by Nils98Ar** [comment]
See: https://bugs.launchpad.net/cinder/+bug/2070475/comments/0.

**Comment by Nils98Ar** [comment]
The column contains always `1` in our case. I will probably try to replace `1` with `true` and re-run `cinder-manage db sync`.

**Comment by osfrickler** [comment]
Just a note: There should be a `cinder-manage.log` file containing the output from the `cinder-manage` command that would contain the failure message regarding the migration.

**Comment by Nils98Ar** [comment]
There is at least no `cinder-manage.log` on the control nodes in `/var/log/kolla`...
