### ISSUE TITLE
osism-kolla deploy grafana fails provisioning a custom dashboard

### ISSUE THREAD

**Issue by linwalth** [osism/issues#241]
Provisioning a custom dashboard fails with the following error during "grafana : Check grafana containers"
```
Traceback (most recent call last):
 File "/tmp/ansible_kolla_docker_payload_dux68q75/ansible_kolla_docker_payload.zip/ansible/modules/kolla_docker.py", line 1241, in main
 File "/tmp/ansible_kolla_docker_payload_dux68q75/ansible_kolla_docker_payload.zip/ansible/modules/kolla_docker.py", line 356, in compare_container
 File "/tmp/ansible_kolla_docker_payload_dux68q75/ansible_kolla_docker_payload.zip/ansible/modules/kolla_docker.py", line 655, in compare_config

Exception: Failed to compare container configuration: ExitCode: 2 

Message: 
INFO:__main__:Loading config file at /var/lib/kolla/config_files/config.json
INFO:__main__:Validating config file
ERROR:__main__:Unexpected error:\nTraceback (most recent call last):
 File "/usr/local/bin/kolla_set_configs", line 435, in main
 execute_config_check(config)
 File "/usr/local/bin/kolla_set_configs", line 421, in execute_config_check
 config_file.check()
 File "/usr/local/bin/kolla_set_configs", line 231, in check
 if not self._cmp_dir(source, dest):
 File "/usr/local/bin/kolla_set_configs", line 211, in _cmp_dir
 if not self._cmp_file(full_path, dest_full_path):
 File "/usr/local/bin/kolla_set_configs", line 169, in _cmp_file
 with open(source, 'rb') as f1, open(dest, 'rb') as f2:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/grafana/dashboards/custom_dashboard.json
```

**Comment by berendt** [comment]
Where was the custom_dashboard.json stored in the configuration repository?

**Comment by linwalth** [comment]
/environments/kolla/files/overlays/grafana
