### ISSUE TITLE
Manila: in victoria release manila-share cannot create the share server

### ISSUE THREAD

**Issue by grawert** [osism/issues#4]
Creating a new share using the `generic` driver is failing, because `manila-share` cannot create a share server. When re-deploying manila with `ussuri` release, the error does not occur, and the share is successfully created and accessible.

```
2021-04-22 08:52:33.143 17 DEBUG oslo_concurrency.lockutils [req-1caaacfd-7d7a-4b22-be39-751b02281004 2f9d0ba75b45471592488115f8a76c2f 291bad8f59474ae59faff6d0a2ac41a1 - - -] Lock "share_manager_d25a4954-ad42-4e10-9650-c5bb7c44175f" acquired by "manila.share.manager.ShareManager._provide_share_server_for_share.<locals>._wrapped_provide_share_server_for_share" :: waited 0.000s inner /var/lib/kolla/venv/lib/python3.8/site-packages/oslo_concurrency/lockutils.py:355
2021-04-22 08:52:33.215 17 DEBUG manila.share.manager [req-1caaacfd-7d7a-4b22-be39-751b02281004 2f9d0ba75b45471592488115f8a76c2f 291bad8f59474ae59faff6d0a2ac41a1 - - -] Using share_server d75c1486-01ff-4e75-bab6-f8ea46bfa17d for share instance 0990470d-89fd-45be-a66d-e4649127ecee _wrapped_provide_share_server_for_share /var/lib/kolla/venv/lib/python3.8/site-packages/manila/share/manager.py:635
2021-04-22 08:52:33.402 17 DEBUG manila.share.drivers.generic [req-1caaacfd-7d7a-4b22-be39-751b02281004 2f9d0ba75b45471592488115f8a76c2f 291bad8f59474ae59faff6d0a2ac41a1 - - -] Creating share server 'd75c1486-01ff-4e75-bab6-f8ea46bfa17d'. _setup_server /var/lib/kolla/venv/lib/python3.8/site-packages/manila/share/drivers/generic.py:895
2021-04-22 08:52:33.479 17 DEBUG oslo_concurrency.lockutils [req-1caaacfd-7d7a-4b22-be39-751b02281004 2f9d0ba75b45471592488115f8a76c2f 291bad8f59474ae59faff6d0a2ac41a1 - - -] Lock "share_manager_d25a4954-ad42-4e10-9650-c5bb7c44175f" released by "manila.share.manager.ShareManager._provide_share_server_for_share.<locals>._wrapped_provide_share_server_for_share" :: held 0.337s inner /var/lib/kolla/venv/lib/python3.8/site-packages/oslo_concurrency/lockutils.py:367
2021-04-22 08:52:33.480 17 ERROR manila.share.manager [req-1caaacfd-7d7a-4b22-be39-751b02281004 2f9d0ba75b45471592488115f8a76c2f 291bad8f59474ae59faff6d0a2ac41a1 - - -] Creation of share instance 0990470d-89fd-45be-a66d-e4649127ecee failed: failed to get share server.
2021-04-22 08:52:33.543 17 INFO manila.message.api [req-1caaacfd-7d7a-4b22-be39-751b02281004 2f9d0ba75b45471592488115f8a76c2f 291bad8f59474ae59faff6d0a2ac41a1 - - -] Creating message record for request_id = req-1caaacfd-7d7a-4b22-be39-751b02281004
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server [req-1caaacfd-7d7a-4b22-be39-751b02281004 2f9d0ba75b45471592488115f8a76c2f 291bad8f59474ae59faff6d0a2ac41a1 - - -] Exception during message handling: TypeError: __init__() got an unexpected keyword argument 'message'
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server Traceback (most recent call last):
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_messaging/rpc/server.py", line 165, in _process_incoming
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_messaging/rpc/dispatcher.py", line 309, in dispatch
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_messaging/rpc/dispatcher.py", line 229, in _do_dispatch
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/manila/share/manager.py", line 193, in wrapped
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     return f(self, *args, **kwargs)
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/manila/utils.py", line 568, in wrapper
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     return func(self, *args, **kwargs)
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/manila/share/manager.py", line 1872, in create_share_instance
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     self.message_api.create(
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     self.force_reraise()
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     six.reraise(self.type_, self.value, self.tb)
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python3.8/dist-packages/six.py", line 703, in reraise
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     raise value
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/manila/share/manager.py", line 1857, in create_share_instance
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     self._provide_share_server_for_share(
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/manila/share/manager.py", line 655, in _provide_share_server_for_share
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     return _wrapped_provide_share_server_for_share()
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_concurrency/lockutils.py", line 360, in inner
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     return f(*args, **kwargs)
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/manila/share/manager.py", line 650, in _wrapped_provide_share_server_for_share
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     self._create_share_server_in_backend(
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/manila/share/manager.py", line 751, in _create_share_server_in_backend
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     share_server = self._setup_server(context, share_server, metadata)
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/manila/share/manager.py", line 3926, in _setup_server
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     self.driver.deallocate_network(context, share_server['id'])
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     self.force_reraise()
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     six.reraise(self.type_, self.value, self.tb)
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python3.8/dist-packages/six.py", line 703, in reraise
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     raise value
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/manila/share/manager.py", line 3874, in _setup_server
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     server_info = self.driver.setup_server(
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/manila/share/driver.py", line 945, in setup_server
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     return self._setup_server(*args, **kwargs)
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/manila/share/drivers/generic.py", line 896, in _setup_server
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     server = self.service_instance_manager.set_up_service_instance(
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/manila/share/drivers/service_instance.py", line 454, in set_up_service_instance
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     server = self._create_service_instance(
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/manila/share/drivers/service_instance.py", line 549, in _create_service_instance
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     service_image_id = self._get_service_image(context)
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/manila/share/drivers/service_instance.py", line 534, in _get_service_image
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     images = [image.id for image in self.image_api.image_list(context)
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/manila/image/glance.py", line 68, in image_list
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     client = glanceclient(context)
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/manila/image/glance.py", line 59, in glanceclient
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     return AUTH_OBJ.get_client(context,
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/manila/common/client_auth.py", line 92, in get_client
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     self.admin_auth = self._load_auth_plugin()
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/manila/common/client_auth.py", line 78, in _load_auth_plugin
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server     raise self.exception_module.Unauthorized(message=msg)
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server TypeError: __init__() got an unexpected keyword argument 'message'
2021-04-22 08:52:33.557 17 ERROR oslo_messaging.rpc.server 
2021-04-22 08:52:39.461 17 DEBUG oslo_service.periodic_task [req-75175c88-ad5f-4171-9c4a-47ac20b367f8 - - - - -] Running periodic task ShareManager._publish_service_capabilities run_periodic_tasks /var/lib/kolla/venv/lib/python3.8/site-packages/oslo_service/periodic_task.py:210
2021-04-22 08:52:39.461 17 DEBUG manila.manager [req-75175c88-ad5f-4171-9c4a-47ac20b367f8 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /var/lib/kolla/venv/lib/python3.8/site-packages/manila/manager.py:152
2021-04-22 08:52:39.466 17 DEBUG oslo_service.periodic_task [req-75175c88-ad5f-4171-9c4a-47ac20b367f8 - - - - -] Running periodic task ShareManager.migration_driver_continue run_periodic_tasks /var/lib/kolla/venv/lib/python3.8/site-packages/oslo_service/periodic_task.py:210
2021-04-22 08:52:39.487 17 DEBUG oslo_service.periodic_task [req-75175c88-ad5f-4171-9c4a-47ac20b367f8 - - - - -] Running periodic task ShareManager._report_driver_status run_periodic_tasks /var/lib/kolla/venv/lib/python3.8/site-packages/oslo_service/periodic_task.py:210
2021-04-22 08:52:39.488 17 INFO manila.share.manager [req-75175c88-ad5f-4171-9c4a-47ac20b367f8 - - - - -] Updating share status
2021-04-22 08:52:39.488 17 DEBUG manila.share.driver [req-75175c88-ad5f-4171-9c4a-47ac20b367f8 - - - - -] Updating share stats. _update_share_stats /var/lib/kolla/venv/lib/python3.8/site-packages/manila/share/driver.py:1271
2021-04-22 08:52:39.528 17 DEBUG oslo_service.periodic_task [req-75175c88-ad5f-4171-9c4a-47ac20b367f8 - - - - -] Running periodic task ShareManager.periodic_share_status_update run_periodic_tasks /var/lib/kolla/venv/lib/python3.8/site-packages/oslo_service/periodic_task.py:210
2021-04-22 08:52:39.528 17 DEBUG manila.share.manager [req-75175c88-ad5f-4171-9c4a-47ac20b367f8 - - - - -] Updating status of share instances. periodic_share_status_update /var/lib/kolla/venv/lib/python3.8/site-packages/manila/share/manager.py:4673
```

**Comment by berendt** [comment]
Needs a little more work. Special Manila Images etc. Is in progress.

**Comment by berendt** [comment]
Manila is not really supported in Kolla.
