### ISSUE TITLE
OSISM 5.2.0: manager container unhealthy

### ISSUE THREAD

**Issue by nerdicbynature** [osism/issues#553]
Hi,

while upgrading we experience the following problem:

```
cd /opt/configuration/environments/manager/
rm -rf .venv
virtualenv -p python3 .venv
source .venv/bin/activate
pip3 install wheel python-gilt
pip3 install -r requirements.txt
export ANSIBLE_ASK_VAULT_PASS=True
osism-apply-configuration
osism-update-manager
```

hangs/fails with
```
TASK [osism.services.manager : Wait for an healthy manager service] ***************************************************************************************************************************************************************************************************************
FAILED - RETRYING: [manager1-dev2-az0.pco.ps-intern.de]: Wait for an healthy manager service (50 retries left).
FAILED - RETRYING: [manager1-dev2-az0.pco.ps-intern.de]: Wait for an healthy manager service (49 retries left).
FAILED - RETRYING: [manager1-dev2-az0.pco.ps-intern.de]: Wait for an healthy manager service (48 retries left).
FAILED - RETRYING: [manager1-dev2-az0.pco.ps-intern.de]: Wait for an healthy manager service (47 retries left).


```

We can see that the manager containers do not become healthy:
```
TASK [osism.services.manager : Wait for an healthy manager service] ***************************************************************************************************************************************************************************************************************
FAILED - RETRYING: [manager1-dev2-az0.pco.ps-intern.de]: Wait for an healthy manager service (50 retries left).
FAILED - RETRYING: [manager1-dev2-az0.pco.ps-intern.de]: Wait for an healthy manager service (49 retries left).
FAILED - RETRYING: [manager1-dev2-az0.pco.ps-intern.de]: Wait for an healthy manager service (48 retries left).
FAILED - RETRYING: [manager1-dev2-az0.pco.ps-intern.de]: Wait for an healthy manager service (47 retries left).


```

Stdoutlog of manager-api-1:
```

ERROR:    Application startup failed. Exiting.
INFO:     Started server process [8]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/usr/local/lib/python3.11/site-packages/osism/api.py", line 73, in startup_event
    nb = pynetbox.api(settings.NETBOX_URL, token=settings.NETBOX_TOKEN)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pynetbox/core/api.py", line 72, in __init__
    base_url = "{}/api".format(url if url[-1] != "/" else url[:-1])
                                      ~~~^^^^
TypeError: 'NoneType' object is not subscriptable
```

Stdoutlog of manager-openstack-1:
```
Usage: celery [OPTIONS] COMMAND [ARGS]...
Try 'celery --help' for help.

Error: Invalid value for '-A' / '--app':
Unable to load celery application.
While trying to load the module osism.tasks.openstack the following error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/utils.py", line 383, in find_app
    sym = symbol_by_name(app, imp=imp)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/utils/imports.py", line 64, in symbol_by_name
    return getattr(module, cls_name) if cls_name else module
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'osism.tasks' has no attribute 'openstack'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/bin/celery.py", line 58, in convert
    return find_app(value)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/utils.py", line 386, in find_app
    sym = imp(app)
          ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
    return imp(module, package=package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/site-packages/osism/tasks/openstack.py", line 12, in <module>
    from osism.tasks import Config, conductor, netbox
  File "/usr/local/lib/python3.11/site-packages/osism/tasks/netbox.py", line 11, in <module>
    from osism.actions import (
  File "/usr/local/lib/python3.11/site-packages/osism/actions/check_configuration.py", line 4, in <module>
    from osism import utils
  File "/usr/local/lib/python3.11/site-packages/osism/utils/__init__.py", line 6, in <module>
    nb = pynetbox.api(settings.NETBOX_URL, token=settings.NETBOX_TOKEN)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pynetbox/core/api.py", line 72, in __init__
    base_url = "{}/api".format(url if url[-1] != "/" else url[:-1])
                                      ~~~^^^^
TypeError: 'NoneType' object is not subscriptable



```

Stdoutlog of manager-listener-1:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/osism/services/listener.py", line 9, in <module>
    from osism import utils
  File "/usr/local/lib/python3.11/site-packages/osism/utils/__init__.py", line 6, in <module>
    nb = pynetbox.api(settings.NETBOX_URL, token=settings.NETBOX_TOKEN)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pynetbox/core/api.py", line 72, in __init__
    base_url = "{}/api".format(url if url[-1] != "/" else url[:-1])
                                      ~~~^^^^
TypeError: 'NoneType' object is not subscriptable
```

Note: We do not use netbox:
```
dragon@manager1-dev2-az0:/opt/configuration$ grep netbox_enable environments/manager/configuration.yml
netbox_enable: false
```

Complete manager configuration.yml:
```
---
##########################
# docker registries

docker_registry: index.docker.io
docker_registry_ansible: quay.io
docker_registry_service: index.docker.io

##########################
# versions

manager_version: 5.2.0


configure_cockpit: false
cockpit_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"

ara_enable: true
ara_server_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"

##########################
# listener

# FIXME: It does not work here to work with inventory groups because
#        the manager's inventory is independent from the rest of the
#        inventory.
#
#        For manager_listener_broker_hosts, a list of IP addresses or
#        hostnames must be set up on which the RabbitMQ Broker can be
#        reached on the control nodes.

manager_listener_broker_hosts: []
manager_listener_broker_username: openstack
manager_listener_broker_uri: "{% for host in manager_listener_broker_hosts %}amqp://{{ manager_listener_broker_username }}:{{ manager_listener_broker_password }}@{{ host }}:5672/{% if not loop.last %};{% endif %}{% endfor %}"

##########################
# netbox

netbox_enable: false
netbox_api_url: "http://{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}:8121"

##########################
# celery

celery_enable: true
flower_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"
osism_api_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"

##########################
# other services

beat_enable: false
flower_enable: false
flower_traefik: false
configuration_git_public_key: ssh-rsa AAAAB............................................................................
```

Kind regards,
André.

**Comment by berendt** [comment]
5.2.0 is not yet ready for use. Please wait for https://github.com/osism/testbed/pull/1641.

**Comment by nerdicbynature** [comment]
Oops, ok thanks. Do you have an ETA?

**Comment by berendt** [comment]
With latest/5.2.0 there should be no more issues in the future with unhealthy services when Netbox is not used.

**Comment by berendt** [comment]
We will add an additional note to the release notes to avoid confusions with the listener service when not used:

```
If the Ironic integration of OSISM is not used, the listener service of the
manager can be deactivated. Set ``enable_listener: false`` in
``environments/manager/configuration.yml``.
```
