### ISSUE TITLE
Nova-Compute InvalidCPUInfo

### ISSUE THREAD

**Issue by zachelnet** [osism/issues#567]
If we try to change the CPU-Model to "Skylake-Server-noTSX-IBRS" the container nova-compute restart with following messages:

```
Error starting thread.: nova.exception.InvalidCPUInfo: Configured CPU model: Skylake-Server-noTSX-IBRS is not compatible with host CPU. Please correct your config and try again. Unacceptable CPU info: CPU doesn't have compatibility.

0

Refer to http://libvirt.org/html/libvirt-libvirt-host.html#virCPUCompareResult
2023-06-22 12:00:41.641 7 ERROR oslo_service.service Traceback (most recent call last):
2023-06-22 12:00:41.641 7 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.10/site-packages/nova/virt/libvirt/driver.py", line 991, in _check_cpu_compatibility
2023-06-22 12:00:41.641 7 ERROR oslo_service.service     self._compare_cpu(cpu, self._get_cpu_info(), None)
2023-06-22 12:00:41.641 7 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.10/site-packages/nova/virt/libvirt/driver.py", line 9983, in _compare_cpu
2023-06-22 12:00:41.641 7 ERROR oslo_service.service     raise exception.InvalidCPUInfo(reason=m % {'ret': ret, 'u': u})
2023-06-22 12:00:41.641 7 ERROR oslo_service.service nova.exception.InvalidCPUInfo: Unacceptable CPU info: CPU doesn't have compatibility.
2023-06-22 12:00:41.641 7 ERROR oslo_service.service 
2023-06-22 12:00:41.641 7 ERROR oslo_service.service 0
2023-06-22 12:00:41.641 7 ERROR oslo_service.service 
2023-06-22 12:00:41.641 7 ERROR oslo_service.service Refer to http://libvirt.org/html/libvirt-libvirt-host.html#virCPUCompareResult
2023-06-22 12:00:41.641 7 ERROR oslo_service.service 
2023-06-22 12:00:41.641 7 ERROR oslo_service.service During handling of the above exception, another exception occurred:
2023-06-22 12:00:41.641 7 ERROR oslo_service.service 
2023-06-22 12:00:41.641 7 ERROR oslo_service.service Traceback (most recent call last):
2023-06-22 12:00:41.641 7 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.10/site-packages/oslo_service/service.py", line 806, in run_service
2023-06-22 12:00:41.641 7 ERROR oslo_service.service     service.start()
2023-06-22 12:00:41.641 7 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.10/site-packages/nova/service.py", line 159, in start
2023-06-22 12:00:41.641 7 ERROR oslo_service.service     self.manager.init_host()
2023-06-22 12:00:41.641 7 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.10/site-packages/nova/compute/manager.py", line 1526, in init_host
2023-06-22 12:00:41.641 7 ERROR oslo_service.service     self.driver.init_host(host=self.host)
2023-06-22 12:00:41.641 7 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.10/site-packages/nova/virt/libvirt/driver.py", line 819, in init_host
2023-06-22 12:00:41.641 7 ERROR oslo_service.service     self._check_cpu_compatibility()
2023-06-22 12:00:41.641 7 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.10/site-packages/nova/virt/libvirt/driver.py", line 997, in _check_cpu_compatibility
2023-06-22 12:00:41.641 7 ERROR oslo_service.service     raise exception.InvalidCPUInfo(msg)
2023-06-22 12:00:41.641 7 ERROR oslo_service.service nova.exception.InvalidCPUInfo: Configured CPU model: Skylake-Server-noTSX-IBRS is not compatible with host CPU. Please correct your config and try again. Unacceptable CPU info: CPU doesn't have compatibility.
2023-06-22 12:00:41.641 7 ERROR oslo_service.service 
2023-06-22 12:00:41.641 7 ERROR oslo_service.service 0
2023-06-22 12:00:41.641 7 ERROR oslo_service.service 
2023-06-22 12:00:41.641 7 ERROR oslo_service.service Refer to http://libvirt.org/html/libvirt-libvirt-host.html#virCPUCompareResult
2023-06-22 12:00:41.641 7 ERROR oslo_service.service 
```

please backport following fixed for this:

https://review.opendev.org/c/openstack/nova/+/870794

Osism Release:5.2
quay.io/osism/nova-libvirt:8.0.0.20230615 
quay.io/osism/nova-compute:26.2.1.20230615

**Comment by berendt** [comment]
We cannot make back ports for our stable releases. We can add a back port to 20231.1/Zed images. The patch will then be included in the next 5.3.0 release.
