### ISSUE TITLE
Keystone/Nova-API Error sqlalchemy: pymysql.err.OperationalError 

### ISSUE THREAD

**Issue by zach-b1** [osism/issues#569]
After up upgrade to Openstack Zed (Release 5.2) see a lot of pymysql OperationalError:

Keystone:
```
Exception during reset or similar: pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool Traceback (most recent call last):
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymysql/connections.py", line 756, in _write_bytes
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool     self._sock.sendall(data)
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool BrokenPipeError: [Errno 32] Broken pipe
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool 
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool During handling of the above exception, another exception occurred:
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool 
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool Traceback (most recent call last):
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 739, in _finalize_fairy
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool     fairy._reset(pool)
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 988, in _reset
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool     pool._dialect.do_rollback(self)
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 682, in do_rollback
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool     dbapi_connection.rollback()
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymysql/connections.py", line 479, in rollback
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool     self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymysql/connections.py", line 814, in _execute_command
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool     self._write_bytes(packet)
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymysql/connections.py", line 759, in _write_bytes
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool     raise err.OperationalError(
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
2023-06-23 04:38:45.891 1032 ERROR sqlalchemy.pool.impl.QueuePool 
```

Nova-api
```
Exception during reset or similar: pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query (timed out)')
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool Traceback (most recent call last):
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymysql/connections.py", line 732, in _read_bytes
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool     data = self._rfile.read(num_bytes)
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool   File "/usr/lib/python3.10/socket.py", line 705, in readinto
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool     return self._sock.recv_into(b)
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/eventlet/greenio/base.py", line 376, in recv_into
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool     return self._recv_loop(self.fd.recv_into, 0, buffer, nbytes, flags)
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/eventlet/greenio/base.py", line 364, in _recv_loop
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool     self._read_trampoline()
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/eventlet/greenio/base.py", line 332, in _read_trampoline
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool     self._trampoline(
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/eventlet/greenio/base.py", line 211, in _trampoline
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool     return trampoline(fd, read=read, write=write, timeout=timeout,
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/eventlet/hubs/__init__.py", line 159, in trampoline
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool     return hub.switch()
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/eventlet/hubs/hub.py", line 313, in switch
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool     return self.greenlet.switch()
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool TimeoutError: timed out
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool 
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool During handling of the above exception, another exception occurred:
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool 
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool Traceback (most recent call last):
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 739, in _finalize_fairy
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool     fairy._reset(pool)
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 988, in _reset
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool     pool._dialect.do_rollback(self)
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 682, in do_rollback
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool     dbapi_connection.rollback()
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymysql/connections.py", line 480, in rollback
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool     self._read_ok_packet()
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool     pkt = self._read_packet()
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymysql/connections.py", line 692, in _read_packet
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool     packet_header = self._read_bytes(4)
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool   File "/var/lib/kolla/venv/lib/python3.10/site-packages/pymysql/connections.py", line 738, in _read_bytes
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool     raise err.OperationalError(
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query (timed out)')
2023-06-22 19:59:34.912 750 ERROR sqlalchemy.pool.impl.QueuePool 
```

**Comment by berendt** [comment]
There are no known general problems with the 5.2 images in the context of MySQL. On the systems we have already converted, we have no problems with MySQL Connections.

**Comment by zach-b1** [comment]
Hi,

I found following bugreport and patch
https://bugs.launchpad.net/nova/+bug/2027755
https://review.opendev.org/c/openstack/nova/+/888513
