### ISSUE TITLE
Error with Neutron 22.0.2-46 + Octavia

### ISSUE THREAD

**Issue by berendt** [osism/issues#688]
Related commit in Neutron:

```
commit 68ecae5ff9a364e41126cb338902f1a36fc9413f
Author: Rodolfo Alonso Hernandez <ralonsoh@redhat.com>
Date:   Mon May 8 18:07:03 2023 +0200

    [OVN] Prevent binding a virtual type port

    A LSP is type=virtual when its IP address is used by other ports
    as allowed address. If a LSP is type=virtual, this port cannot be
    bound (that means cannot be used as a port for a virtual machine).

    Closes-Bug: #2018529
    Change-Id: I1943e6e0d7d8e255e95f93881cc3caec16ab67fe
```

Error in Octavia:

```
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker [-] LB e33eff2b-e0df-4bfb-900d-c2e8160ec533 failover exception: Bad port request: A virtual logical switch port cannot be bound to a host.
Neutron server returns request_ids: ['req-02ac2c5d-3041-44ce-aebc-78585b79e420']: octavia.network.base.PlugVIPException: Bad port request: A virtual logical switch port cannot be bound to a host.
Neutron server returns request_ids: ['req-02ac2c5d-3041-44ce-aebc-78585b79e420']
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker Traceback (most recent call last):
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker   File "/var/lib/kolla/venv/lib/python3.10/site-packages/octavia/network/drivers/neutron/base.py", line 139, in _add_security_group_to_port
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker     self.neutron_client.update_port(port_id, port_update)
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker   File "/var/lib/kolla/venv/lib/python3.10/site-packages/neutronclient/v2_0/client.py", line 828, in update_port
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker     return self._update_resource(self.port_path % (port), body=body,
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker   File "/var/lib/kolla/venv/lib/python3.10/site-packages/neutronclient/v2_0/client.py", line 2548, in _update_resource
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker     return self.put(path, **kwargs)
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker   File "/var/lib/kolla/venv/lib/python3.10/site-packages/neutronclient/v2_0/client.py", line 365, in put
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker     return self.retry_request("PUT", action, body=body,
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker   File "/var/lib/kolla/venv/lib/python3.10/site-packages/neutronclient/v2_0/client.py", line 333, in retry_request
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker     return self.do_request(method, action, body=body,
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker   File "/var/lib/kolla/venv/lib/python3.10/site-packages/neutronclient/v2_0/client.py", line 297, in do_request
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker     self._handle_fault_response(status_code, replybody, resp)
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker   File "/var/lib/kolla/venv/lib/python3.10/site-packages/neutronclient/v2_0/client.py", line 272, in _handle_fault_response
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker     exception_handler_v20(status_code, error_body)
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker   File "/var/lib/kolla/venv/lib/python3.10/site-packages/neutronclient/v2_0/client.py", line 90, in exception_handler_v20
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker     raise client_exc(message=error_message,
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker neutronclient.common.exceptions.BadRequest: Bad port request: A virtual logical switch port cannot be bound to a host.
2023-09-30 20:20:31.357 22 ERROR octavia.controller.worker.v2.controller_worker Neutron server returns request_ids: ['req-02ac2c5d-3041-44ce-aebc-78585b79e420']
```

**Comment by berendt** [comment]
This only happens when using "octavia_auto_configure: 'no'" without adding the required amp_image_owner_id, amp_boot_network_list, ... to the octavia.conf overlay. Will be documented.

**Comment by maliblatt** [comment]
seems that we hit this bug with 6.0.0. I put amp_image_owner_id into the overlay file (amp_boot_network_list was already there), but still we get the error `octavia.network.base.PlugVIPException: Bad port request: A virtual logical switch port cannot be bound to a host.` when trying to do some octavia actions.
Will this be resolved with the patch in https://github.com/osism/container-images-kolla/pull/360 ? Will this go to a 6.0.1 release?

**Comment by berendt** [comment]
Thanks for testing. I will merge the mentioned PR tomorrow and add another note to the release notes.

After the merge of 360 you can overwrite the used neutron service image in environment/kolla/images.yml for the moment. I think it makes sense to wait for more tests until we build a 6.0.1.
