### ISSUE TITLE
Ironic Endpoint Issue

### ISSUE THREAD

**Issue by rmueller-b1** [osism/issues#716]
Hello,

we successfully deployed Ironic in a Zed OSISM enviornment. Currently we have the issue that the `ironic_neutron_server` does not become healthy. In the logs we see the following error:

```
2023-10-12 10:32:39.775 7 ERROR oslo_service.service Traceback (most recent call last):
2023-10-12 10:32:39.775 7 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.10/site-packages/oslo_service/service.py", line 806, in run_service
2023-10-12 10:32:39.775 7 ERROR oslo_service.service     service.start()
2023-10-12 10:32:39.775 7 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.10/site-packages/ironic_inspector/common/rpc_service.py", line 40, in start
2023-10-12 10:32:39.775 7 ERROR oslo_service.service     self.manager.init_host()
2023-10-12 10:32:39.775 7 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.10/site-packages/ironic_inspector/conductor/manager.py", line 100, in init_host
2023-10-12 10:32:39.775 7 ERROR oslo_service.service     driver.init_filter()
2023-10-12 10:32:39.775 7 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.10/site-packages/ironic_inspector/pxe_filter/base.py", line 87, in inner
2023-10-12 10:32:39.775 7 ERROR oslo_service.service     return method(self, *args, **kwargs)
2023-10-12 10:32:39.775 7 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.10/site-packages/ironic_inspector/pxe_filter/dnsmasq.py", line 150, in init_filter
2023-10-12 10:32:39.775 7 ERROR oslo_service.service     ironic = ir_utils.get_client()
2023-10-12 10:32:39.775 7 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.10/site-packages/ironic_inspector/common/ironic.py", line 62, in get_client
2023-10-12 10:32:39.775 7 ERROR oslo_service.service     session=session, oslo_conf=CONF).baremetal
2023-10-12 10:32:39.775 7 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.10/site-packages/openstack/service_description.py", line 87, in __get__
2023-10-12 10:32:39.775 7 ERROR oslo_service.service     proxy = self._make_proxy(instance)
2023-10-12 10:32:39.775 7 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.10/site-packages/openstack/service_description.py", line 266, in _make_proxy
2023-10-12 10:32:39.775 7 ERROR oslo_service.service     raise exceptions.NotSupported(
2023-10-12 10:32:39.775 7 ERROR oslo_service.service openstack.exceptions.NotSupported: The baremetal service for api-int.kvnurs.intra:RegionOne exists but does not have any supported versions.
2023-10-12 10:32:39.775 7 ERROR oslo_service.service
```

We tried to add a certificate to the Ironic and Neutron containers but this did not solve the issue and the error message did not change.

Is this due to a change from Yoga to Zed? We are using the same configuration as in a different Cloud that is currently running on Yoga. I was not able to find anything related in the release notes of Kolla.

Regards,
Robert Müller

**Comment by rmueller-b1** [comment]
Does the Ironic container contain the sushi library?

**Comment by berendt** [comment]
> Does the Ironic container contain the sushi library?

```
$ docker run --rm -it quay.io/osism/ironic-api:2023.1 pip3 list | grep sushy
sushy                   4.4.2
```

**Comment by berendt** [comment]
I'll close here. Since no feedback has been received so far, I assume that the problems will no longer occur with the current version of Ironic.
