### ISSUE TITLE
osism reconciler randomly stops working and emit utf8 errors

### ISSUE THREAD

**Issue by nerdicbynature** [osism/issues#780]
Hi,

I randomly get the following error while running **osism reconciler sync**:

```
dragon@manager1:/opt/configuration/inventory$ osism reconciler sync
2023-11-29 20:18:48 | INFO     | Task e25ea240-e26d-466b-b831-2e8056f03d25 is running in background. Output coming soon.
2023-11-29 20:18:49 | INFO     | Writing 050-kolla-ceph-rgw-hosts.yml with ceph_rgw_hosts
2023-11-29 20:18:49 | INFO     | Writing 050-infrastructure-cephclient-mons.yml with cephclient_mons
Traceback (most recent call last):
  File "/handle-inventory-overwrite.py", line 41, in <module>
    config.read(os.path.join(f))
  File "/usr/local/lib/python3.12/configparser.py", line 684, in read
    self._read(fp, filename)
  File "/usr/local/lib/python3.12/configparser.py", line 998, in _read
    for lineno, line in enumerate(fp, start=1):
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 17: invalid start byte
```

Workaround: docker restart manager-inventory_reconciler-1

Kind regards,
André.

**Comment by berendt** [comment]
I will output the related file. Please check if the related file has a newline at the EOF.

**Comment by berendt** [comment]
Your problem is probably fixed with the 2nd PR.

**Comment by nerdicbynature** [comment]
Okay, thank you for the quick reaction :)
