### ISSUE TITLE
Calling cinder-manage quota sync causes a failure

### ISSUE THREAD

**Issue by osfrickler** [osism/issues#811]
The log is hidden within `/var/log/kolla/cinder/cinder-api.log` when running the command inside the `cinder_api` container.

```
2023-12-29 11:59:19.915 23732 CRITICAL cinder [None req-f36408c4-5ab0-4ad3-837a-e2172acc5f8a - - - - - -] Unhandled error: sqlalchemy.exc.ArgumentError: Textual column expression 'project_id' should be explicitly declared with text('project_id'), or use column('project_id') for more specificity
2023-12-29 11:59:19.915 23732 ERROR cinder Traceback (most recent call last):
2023-12-29 11:59:19.915 23732 ERROR cinder   File "/var/lib/kolla/venv/bin/cinder-manage", line 8, in <module>
2023-12-29 11:59:19.915 23732 ERROR cinder     sys.exit(main())
2023-12-29 11:59:19.915 23732 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/cinder/cmd/manage.py", line 1151, in main
2023-12-29 11:59:19.915 23732 ERROR cinder     fn(**fn_kwargs)
2023-12-29 11:59:19.915 23732 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/cinder/cmd/manage.py", line 364, in check
2023-12-29 11:59:19.915 23732 ERROR cinder     result = self._check_sync(project_id, do_fix=False)
2023-12-29 11:59:19.915 23732 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/cinder/cmd/manage.py", line 506, in _check_sync
2023-12-29 11:59:19.915 23732 ERROR cinder     projects = self._get_quota_projects(ctxt, project_id)
2023-12-29 11:59:19.915 23732 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/oslo_db/sqlalchemy/enginefacade.py", line 1022, in wrapper
2023-12-29 11:59:19.915 23732 ERROR cinder     return fn(*args, **kwargs)
2023-12-29 11:59:19.915 23732 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/cinder/cmd/manage.py", line 415, in _get_quota_projects
2023-12-29 11:59:19.915 23732 ERROR cinder     ).with_entities('project_id').distinct().all()
2023-12-29 11:59:19.915 23732 ERROR cinder   File "<string>", line 2, in with_entities
2023-12-29 11:59:19.915 23732 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 110, in _generative
2023-12-29 11:59:19.915 23732 ERROR cinder     x = fn(self, *args, **kw)
2023-12-29 11:59:19.915 23732 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 1452, in with_entities
2023-12-29 11:59:19.915 23732 ERROR cinder     self._set_entities(entities)
2023-12-29 11:59:19.915 23732 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 187, in _set_entities
2023-12-29 11:59:19.915 23732 ERROR cinder     self._raw_columns = [
2023-12-29 11:59:19.915 23732 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 188, in <listcomp>
2023-12-29 11:59:19.915 23732 ERROR cinder     coercions.expect(
2023-12-29 11:59:19.915 23732 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 188, in expect
2023-12-29 11:59:19.915 23732 ERROR cinder     resolved = impl._literal_coercion(
2023-12-29 11:59:19.915 23732 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 388, in _literal_coercion
2023-12-29 11:59:19.915 23732 ERROR cinder     return self._text_coercion(element, argname, **kw)
2023-12-29 11:59:19.915 23732 ERROR cinder   File "/var/lib/kolla/venv/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 841, in _text_coercion
2023-12-29 11:59:19.915 23732 ERROR cinder     raise exc.ArgumentError(
2023-12-29 11:59:19.915 23732 ERROR cinder sqlalchemy.exc.ArgumentError: Textual column expression 'project_id' should be explicitly declared with text('project_id'), or use column('project_id') for more specificity
2023-12-29 11:59:19.915 23732 ERROR cinder
```

Reproduced with devstack on master and reported upstream bug: https://bugs.launchpad.net/cinder/+bug/2047693

**Comment by osfrickler** [comment]
Proposed fixes:

Fix error in cinder-manage quota sync cmd  https://review.opendev.org/c/openstack/cinder/+/904451
Add test for cinder-manage quota sync  https://review.opendev.org/c/openstack/cinder/+/904453
Fix issue with listing quota projects  https://review.opendev.org/c/openstack/cinder/+/904456

**Comment by osfrickler** [comment]
Fix for actually committing quota fixes to the DB https://review.opendev.org/c/openstack/cinder/+/904487

**Comment by berendt** [comment]
- [ ] add docs how to check & sync the quota of projects
