### ISSUE TITLE
Unable to create loadbalancer with provider amphora

### ISSUE THREAD

**Issue by mario-minners** [osism/issues#919]
Hi,
since the upgrade to 7.0.0d the amphora provider can't create load balancers anymore, with ovn all works fine.

In the octavia-worker.log we see an massive amount of errors that are complaining about an non existent logbook.
```
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor Traceback (most recent call last):
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor   File "/var/lib/kolla/venv/lib/python3.10/site-packages/taskflow/conductors/backends/impl_executor.py", line 239, in _on_job_done
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor     consume = fut.result()
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor     return self.__get_result()
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor     raise self._exception
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor   File "/var/lib/kolla/venv/lib/python3.10/site-packages/futurist/_utils.py", line 45, in run
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor     result = self.fn(*self.args, **self.kwargs)
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor   File "/var/lib/kolla/venv/lib/python3.10/site-packages/taskflow/conductors/backends/impl_executor.py", line 149, in _dispatch_job
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor     engine = self._engine_from_job(job)
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor   File "/var/lib/kolla/venv/lib/python3.10/site-packages/taskflow/conductors/base.py", line 112, in _engine_from_job
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor     flow_detail = self._flow_detail_from_job(job)
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor   File "/var/lib/kolla/venv/lib/python3.10/site-packages/taskflow/conductors/base.py", line 89, in _flow_detail_from_job
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor     book = job.book
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor   File "/var/lib/kolla/venv/lib/python3.10/site-packages/taskflow/jobs/base.py", line 214, in book
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor     self._book = self._load_book()
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor   File "/var/lib/kolla/venv/lib/python3.10/site-packages/taskflow/jobs/base.py", line 263, in _load_book
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor     return conn.get_logbook(book_uuid)
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor   File "/var/lib/kolla/venv/lib/python3.10/site-packages/taskflow/persistence/backends/impl_sqlalchemy.py", line 544, in get_logbook
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor     raise exc.NotFound("No logbook found with"
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor taskflow.exceptions.NotFound: No logbook found with uuid '5bc64974-9ad5-418b-8a61-f3a17dfff4a9'
2024-03-15 14:49:47.225 1638 ERROR taskflow.conductors.backends.impl_executor
```

At this time we only found one reference to that:
https://bugs.launchpad.net/octavia/+bug/2046207

This only happens in one of two environments that are upgraded to 7.0.0d. There is a fifty fifty chance that this error is caused by a very old installation in the gx-scs environment.

**Comment by berendt** [comment]
Workaround: disable jobboard in environments/kolla/configuration.yml.

```
enable_octavia_jobboard: "no"
```

Depends on a back port of https://review.opendev.org/c/openstack/kolla-ansible/+/913410
