### ISSUE TITLE
Make Ubuntu 24.04 usable in Zuul CI

### ISSUE THREAD

**Issue by berendt** [osism/issues#956]
Ubuntu 24.04 will be out soon. Should be usable in the Zuul CI.

**Comment by osfrickler** [comment]
Initial attempt failed because debootstrap on bookworm doesn't know about noble, support was only added to the latest version in master https://salsa.debian.org/installer-team/debootstrap/-/commit/1223abb5e0c02f9145002e5838f909fe69bbb403.

Workaround: Manually add the symlink in the nodepool builder container.

**Comment by osfrickler** [comment]
Next failure, glean installation is broken:

```
2024-04-15 07:22:31.436 | + glean-install
2024-04-15 07:22:31.463 | Traceback (most recent call last):
2024-04-15 07:22:31.463 |   File "/usr/local/bin/glean-install", line 5, in <module>
2024-04-15 07:22:31.463 |     from glean.install import main
2024-04-15 07:22:31.463 |   File "/usr/glean/lib/python3.12/site-packages/glean/install.py", line 19, in <module>
2024-04-15 07:22:31.463 |     import pkg_resources
2024-04-15 07:22:31.463 | ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by osfrickler** [comment]
Tested https://review.opendev.org/c/opendev/glean/+/915907 and it resolves the issue

**Comment by osfrickler** [comment]
Further upstream fix needed https://review.opendev.org/c/openstack/project-config/+/916050. With that applied, image build succeeds and image can be booted.

**Comment by osfrickler** [comment]
This is the codification of the initial workaround:

https://review.opendev.org/c/zuul/nodepool/+/916053 Make debootstrap support noble

**Comment by osfrickler** [comment]
Testing in dib https://review.opendev.org/c/openstack/diskimage-builder/+/915915

**Comment by osfrickler** [comment]
Node type has been added to OSISM Zuul, testing in https://github.com/osism/ansible-collection-commons/pull/619

**Comment by osfrickler** [comment]
Image seems to be working fine
